/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoActivateDraftSubscriptionRequest,
  DtoActivateDraftSubscriptionRequest$Outbound,
  DtoActivateDraftSubscriptionRequest$outboundSchema,
} from "./dto-activate-draft-subscription-request.js";

export type ActivateSubscriptionRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Activate Draft Subscription Request
   */
  body: DtoActivateDraftSubscriptionRequest;
};

/** @internal */
export type ActivateSubscriptionRequest$Outbound = {
  id: string;
  body: DtoActivateDraftSubscriptionRequest$Outbound;
};

/** @internal */
export const ActivateSubscriptionRequest$outboundSchema: z.ZodMiniType<
  ActivateSubscriptionRequest$Outbound,
  ActivateSubscriptionRequest
> = z.object({
  id: z.string(),
  body: DtoActivateDraftSubscriptionRequest$outboundSchema,
});

export function activateSubscriptionRequestToJSON(
  activateSubscriptionRequest: ActivateSubscriptionRequest,
): string {
  return JSON.stringify(
    ActivateSubscriptionRequest$outboundSchema.parse(
      activateSubscriptionRequest,
    ),
  );
}
