/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  LineItemCommitmentConfig,
  LineItemCommitmentConfig$Outbound,
  LineItemCommitmentConfig$outboundSchema,
} from "./line-item-commitment-config.js";

export type AddAddonToSubscriptionRequest = {
  addonId: string;
  /**
   * LineItemCommitments allows setting commitment configuration per addon line item (keyed by price_id)
   */
  lineItemCommitments?: { [k: string]: LineItemCommitmentConfig } | undefined;
  metadata?: { [k: string]: any } | undefined;
  startDate?: Date | undefined;
};

/** @internal */
export type AddAddonToSubscriptionRequest$Outbound = {
  addon_id: string;
  line_item_commitments?:
    | { [k: string]: LineItemCommitmentConfig$Outbound }
    | undefined;
  metadata?: { [k: string]: any } | undefined;
  start_date?: string | undefined;
};

/** @internal */
export const AddAddonToSubscriptionRequest$outboundSchema: z.ZodMiniType<
  AddAddonToSubscriptionRequest$Outbound,
  AddAddonToSubscriptionRequest
> = z.pipe(
  z.object({
    addonId: z.string(),
    lineItemCommitments: z.optional(
      z.record(z.string(), LineItemCommitmentConfig$outboundSchema),
    ),
    metadata: z.optional(z.record(z.string(), z.any())),
    startDate: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      addonId: "addon_id",
      lineItemCommitments: "line_item_commitments",
      startDate: "start_date",
    });
  }),
);

export function addAddonToSubscriptionRequestToJSON(
  addAddonToSubscriptionRequest: AddAddonToSubscriptionRequest,
): string {
  return JSON.stringify(
    AddAddonToSubscriptionRequest$outboundSchema.parse(
      addAddonToSubscriptionRequest,
    ),
  );
}
