/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  ChangedSubscriptionAction,
  ChangedSubscriptionAction$inboundSchema,
} from "./changed-subscription-action.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$inboundSchema,
} from "./subscription-status.js";

export type ChangedSubscription = {
  /**
   * created | updated
   */
  action?: ChangedSubscriptionAction | undefined;
  id?: string | undefined;
  status?: SubscriptionStatus | undefined;
};

/** @internal */
export const ChangedSubscription$inboundSchema: z.ZodMiniType<
  ChangedSubscription,
  unknown
> = z.object({
  action: types.optional(ChangedSubscriptionAction$inboundSchema),
  id: types.optional(types.string()),
  status: types.optional(SubscriptionStatus$inboundSchema),
});

export function changedSubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<ChangedSubscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChangedSubscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChangedSubscription' from JSON`,
  );
}
