/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { Price, Price$inboundSchema } from "./price.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type CreateBulkPriceResponse = {
  items?: Array<Price> | undefined;
};

/** @internal */
export const CreateBulkPriceResponse$inboundSchema: z.ZodMiniType<
  CreateBulkPriceResponse,
  unknown
> = z.object({
  items: types.optional(z.array(Price$inboundSchema)),
});

export function createBulkPriceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBulkPriceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBulkPriceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBulkPriceResponse' from JSON`,
  );
}
