/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  FilterCondition,
  FilterCondition$Outbound,
  FilterCondition$outboundSchema,
} from "./filter-condition.js";
import {
  SortCondition,
  SortCondition$Outbound,
  SortCondition$outboundSchema,
} from "./sort-condition.js";
import { Status, Status$outboundSchema } from "./status.js";

export const CustomerFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type CustomerFilterOrder = ClosedEnum<typeof CustomerFilterOrder>;

export type CustomerFilter = {
  customerIds?: Array<string> | undefined;
  email?: string | undefined;
  endTime?: string | undefined;
  expand?: string | undefined;
  externalId?: string | undefined;
  externalIds?: Array<string> | undefined;
  filters?: Array<FilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: CustomerFilterOrder | undefined;
  parentCustomerIds?: Array<string> | undefined;
  sort?: Array<SortCondition> | undefined;
  startTime?: string | undefined;
  status?: Status | undefined;
};

/** @internal */
export const CustomerFilterOrder$outboundSchema: z.ZodMiniEnum<
  typeof CustomerFilterOrder
> = z.enum(CustomerFilterOrder);

/** @internal */
export type CustomerFilter$Outbound = {
  customer_ids?: Array<string> | undefined;
  email?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_id?: string | undefined;
  external_ids?: Array<string> | undefined;
  filters?: Array<FilterCondition$Outbound> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  parent_customer_ids?: Array<string> | undefined;
  sort?: Array<SortCondition$Outbound> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const CustomerFilter$outboundSchema: z.ZodMiniType<
  CustomerFilter$Outbound,
  CustomerFilter
> = z.pipe(
  z.object({
    customerIds: z.optional(z.array(z.string())),
    email: z.optional(z.string()),
    endTime: z.optional(z.string()),
    expand: z.optional(z.string()),
    externalId: z.optional(z.string()),
    externalIds: z.optional(z.array(z.string())),
    filters: z.optional(z.array(FilterCondition$outboundSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    order: z.optional(CustomerFilterOrder$outboundSchema),
    parentCustomerIds: z.optional(z.array(z.string())),
    sort: z.optional(z.array(SortCondition$outboundSchema)),
    startTime: z.optional(z.string()),
    status: z.optional(Status$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      customerIds: "customer_ids",
      endTime: "end_time",
      externalId: "external_id",
      externalIds: "external_ids",
      parentCustomerIds: "parent_customer_ids",
      startTime: "start_time",
    });
  }),
);

export function customerFilterToJSON(customerFilter: CustomerFilter): string {
  return JSON.stringify(CustomerFilter$outboundSchema.parse(customerFilter));
}
