/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteSubscriptionLineItemRequest = {
  effectiveFrom?: string | undefined;
};

/** @internal */
export type DeleteSubscriptionLineItemRequest$Outbound = {
  effective_from?: string | undefined;
};

/** @internal */
export const DeleteSubscriptionLineItemRequest$outboundSchema: z.ZodMiniType<
  DeleteSubscriptionLineItemRequest$Outbound,
  DeleteSubscriptionLineItemRequest
> = z.pipe(
  z.object({
    effectiveFrom: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      effectiveFrom: "effective_from",
    });
  }),
);

export function deleteSubscriptionLineItemRequestToJSON(
  deleteSubscriptionLineItemRequest: DeleteSubscriptionLineItemRequest,
): string {
  return JSON.stringify(
    DeleteSubscriptionLineItemRequest$outboundSchema.parse(
      deleteSubscriptionLineItemRequest,
    ),
  );
}
