/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoDeleteSubscriptionLineItemRequest,
  DtoDeleteSubscriptionLineItemRequest$Outbound,
  DtoDeleteSubscriptionLineItemRequest$outboundSchema,
} from "./dto-delete-subscription-line-item-request.js";

export type DeleteSubscriptionLineItemRequest = {
  /**
   * Line Item ID
   */
  id: string;
  /**
   * Delete Line Item Request
   */
  body: DtoDeleteSubscriptionLineItemRequest;
};

/** @internal */
export type DeleteSubscriptionLineItemRequest$Outbound = {
  id: string;
  body: DtoDeleteSubscriptionLineItemRequest$Outbound;
};

/** @internal */
export const DeleteSubscriptionLineItemRequest$outboundSchema: z.ZodMiniType<
  DeleteSubscriptionLineItemRequest$Outbound,
  DeleteSubscriptionLineItemRequest
> = z.object({
  id: z.string(),
  body: DtoDeleteSubscriptionLineItemRequest$outboundSchema,
});

export function deleteSubscriptionLineItemRequestToJSON(
  deleteSubscriptionLineItemRequest: DeleteSubscriptionLineItemRequest,
): string {
  return JSON.stringify(
    DeleteSubscriptionLineItemRequest$outboundSchema.parse(
      deleteSubscriptionLineItemRequest,
    ),
  );
}
