/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$inboundSchema,
} from "./dto-invoice-response.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./pagination-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type DtoListInvoicesResponse = {
  items?: Array<DtoInvoiceResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListInvoicesResponse$inboundSchema: z.ZodMiniType<
  DtoListInvoicesResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoInvoiceResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function dtoListInvoicesResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListInvoicesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListInvoicesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListInvoicesResponse' from JSON`,
  );
}
