/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type DtoFeatureUsageInfo = {
  customerId?: string | undefined;
  featureId?: string | undefined;
  meterId?: string | undefined;
  priceId?: string | undefined;
  processedAt?: string | undefined;
  qtyTotal?: string | undefined;
  subLineItemId?: string | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export const DtoFeatureUsageInfo$inboundSchema: z.ZodMiniType<
  DtoFeatureUsageInfo,
  unknown
> = z.pipe(
  z.object({
    customer_id: types.optional(types.string()),
    feature_id: types.optional(types.string()),
    meter_id: types.optional(types.string()),
    price_id: types.optional(types.string()),
    processed_at: types.optional(types.string()),
    qty_total: types.optional(types.string()),
    sub_line_item_id: types.optional(types.string()),
    subscription_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "customer_id": "customerId",
      "feature_id": "featureId",
      "meter_id": "meterId",
      "price_id": "priceId",
      "processed_at": "processedAt",
      "qty_total": "qtyTotal",
      "sub_line_item_id": "subLineItemId",
      "subscription_id": "subscriptionId",
    });
  }),
);

export function dtoFeatureUsageInfoFromJSON(
  jsonString: string,
): SafeParseResult<DtoFeatureUsageInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoFeatureUsageInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoFeatureUsageInfo' from JSON`,
  );
}
