/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  BillingCadence,
  BillingCadence$inboundSchema,
} from "./billing-cadence.js";
import { BillingCycle, BillingCycle$inboundSchema } from "./billing-cycle.js";
import {
  BillingPeriod,
  BillingPeriod$inboundSchema,
} from "./billing-period.js";
import {
  DtoCouponAssociationResponse,
  DtoCouponAssociationResponse$inboundSchema,
} from "./dto-coupon-association-response.js";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$inboundSchema,
} from "./dto-credit-grant-response.js";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$inboundSchema,
} from "./dto-customer-response.js";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$inboundSchema,
} from "./dto-invoice-response.js";
import {
  DtoPlanResponse,
  DtoPlanResponse$inboundSchema,
} from "./dto-plan-response.js";
import {
  DtoSubscriptionPhaseResponse,
  DtoSubscriptionPhaseResponse$inboundSchema,
} from "./dto-subscription-phase-response.js";
import { PauseStatus, PauseStatus$inboundSchema } from "./pause-status.js";
import { PaymentTerms, PaymentTerms$inboundSchema } from "./payment-terms.js";
import {
  ProrationBehavior,
  ProrationBehavior$inboundSchema,
} from "./proration-behavior.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import { Status, Status$inboundSchema } from "./status.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$inboundSchema,
} from "./subscription-status.js";
import {
  SubscriptionSubscriptionLineItem,
  SubscriptionSubscriptionLineItem$inboundSchema,
} from "./subscription-subscription-line-item.js";
import {
  SubscriptionSubscriptionPause,
  SubscriptionSubscriptionPause$inboundSchema,
} from "./subscription-subscription-pause.js";

export type DtoSubscriptionResponse = {
  /**
   * ActivePauseID references the current active pause configuration
   *
   * @remarks
   * This will be null if no pause is active or scheduled
   */
  activePauseId?: string | undefined;
  /**
   * BillingAnchor is the reference point that aligns future billing cycle dates.
   *
   * @remarks
   * It sets the day of week for week intervals, the day of month for month and year intervals,
   * and the month of year for year intervals. The timestamp is in UTC format.
   */
  billingAnchor?: string | undefined;
  billingCadence?: BillingCadence | undefined;
  billingCycle?: BillingCycle | undefined;
  billingPeriod?: BillingPeriod | undefined;
  /**
   * BillingPeriodCount is the total number units of the billing period.
   */
  billingPeriodCount?: number | undefined;
  /**
   * CancelAt is the date the subscription will be canceled
   */
  cancelAt?: string | undefined;
  /**
   * CancelAtPeriodEnd is whether the subscription was canceled at the end of the current period
   */
  cancelAtPeriodEnd?: boolean | undefined;
  /**
   * CanceledAt is the date the subscription was canceled
   */
  cancelledAt?: string | undefined;
  /**
   * CollectionMethod determines how invoices are collected
   */
  collectionMethod?: string | undefined;
  /**
   * CommitmentAmount is the minimum amount a customer commits to paying for a billing period
   */
  commitmentAmount?: string | undefined;
  commitmentDuration?: BillingPeriod | undefined;
  /**
   * CouponAssociations are the coupon associations for this subscription
   */
  couponAssociations?: Array<DtoCouponAssociationResponse> | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  /**
   * Credit grants are the credit grants for this subscription
   */
  creditGrants?: Array<DtoCreditGrantResponse> | undefined;
  /**
   * Currency is the currency of the subscription in lowercase 3 digit ISO codes
   */
  currency?: string | undefined;
  /**
   * CurrentPeriodEnd is the end of the current period that the subscription has been invoiced for.
   *
   * @remarks
   * At the end of this period, a new invoice will be created.
   */
  currentPeriodEnd?: string | undefined;
  /**
   * CurrentPeriodStart is the end of the current period that the subscription has been invoiced for.
   *
   * @remarks
   * At the end of this period, a new invoice will be created.
   */
  currentPeriodStart?: string | undefined;
  /**
   * Customer response object containing all customer information
   */
  customer?: DtoCustomerResponse | undefined;
  /**
   * CustomerID is the identifier for the customer in our system
   */
  customerId?: string | undefined;
  customerTimezone?: string | undefined;
  enableTrueUp?: boolean | undefined;
  /**
   * EndDate is the end date of the subscription
   */
  endDate?: string | undefined;
  /**
   * EnvironmentID is the environment identifier for the subscription
   */
  environmentId?: string | undefined;
  /**
   * GatewayPaymentMethodID is the gateway payment method ID for this subscription
   */
  gatewayPaymentMethodId?: string | undefined;
  /**
   * ID is the unique identifier for the subscription
   */
  id?: string | undefined;
  /**
   * InvoicingCustomerID is the customer ID to use for invoicing
   *
   * @remarks
   * This can differ from the subscription customer (e.g., parent company invoicing for child company)
   */
  invoicingCustomerId?: string | undefined;
  latestInvoice?: DtoInvoiceResponse | undefined;
  lineItems?: Array<SubscriptionSubscriptionLineItem> | undefined;
  /**
   * LookupKey is the key used to lookup the subscription in our system
   */
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  /**
   * OverageFactor is a multiplier applied to usage beyond the commitment amount
   */
  overageFactor?: string | undefined;
  /**
   * ParentSubscriptionID is the parent subscription ID for hierarchy (e.g. child subscription under a parent)
   */
  parentSubscriptionId?: string | undefined;
  pauseStatus?: PauseStatus | undefined;
  pauses?: Array<SubscriptionSubscriptionPause> | undefined;
  /**
   * PaymentBehavior determines how subscription payments are handled
   */
  paymentBehavior?: string | undefined;
  paymentTerms?: PaymentTerms | undefined;
  /**
   * Phases are the subscription phases for this subscription
   */
  phases?: Array<DtoSubscriptionPhaseResponse> | undefined;
  plan?: DtoPlanResponse | undefined;
  /**
   * PlanID is the identifier for the plan in our system
   */
  planId?: string | undefined;
  prorationBehavior?: ProrationBehavior | undefined;
  /**
   * StartDate is the start date of the subscription
   */
  startDate?: string | undefined;
  status?: Status | undefined;
  subscriptionStatus?: SubscriptionStatus | undefined;
  tenantId?: string | undefined;
  /**
   * TrialEnd is the end date of the trial period
   */
  trialEnd?: string | undefined;
  /**
   * TrialStart is the start date of the trial period
   */
  trialStart?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
  /**
   * Version is used for optimistic locking
   */
  version?: number | undefined;
};

/** @internal */
export const DtoSubscriptionResponse$inboundSchema: z.ZodMiniType<
  DtoSubscriptionResponse,
  unknown
> = z.pipe(
  z.object({
    active_pause_id: types.optional(types.string()),
    billing_anchor: types.optional(types.string()),
    billing_cadence: types.optional(BillingCadence$inboundSchema),
    billing_cycle: types.optional(BillingCycle$inboundSchema),
    billing_period: types.optional(BillingPeriod$inboundSchema),
    billing_period_count: types.optional(types.number()),
    cancel_at: types.optional(types.string()),
    cancel_at_period_end: types.optional(types.boolean()),
    cancelled_at: types.optional(types.string()),
    collection_method: types.optional(types.string()),
    commitment_amount: types.optional(types.string()),
    commitment_duration: types.optional(BillingPeriod$inboundSchema),
    coupon_associations: types.optional(
      z.array(DtoCouponAssociationResponse$inboundSchema),
    ),
    created_at: types.optional(types.string()),
    created_by: types.optional(types.string()),
    credit_grants: types.optional(
      z.array(DtoCreditGrantResponse$inboundSchema),
    ),
    currency: types.optional(types.string()),
    current_period_end: types.optional(types.string()),
    current_period_start: types.optional(types.string()),
    customer: types.optional(DtoCustomerResponse$inboundSchema),
    customer_id: types.optional(types.string()),
    customer_timezone: types.optional(types.string()),
    enable_true_up: types.optional(types.boolean()),
    end_date: types.optional(types.string()),
    environment_id: types.optional(types.string()),
    gateway_payment_method_id: types.optional(types.string()),
    id: types.optional(types.string()),
    invoicing_customer_id: types.optional(types.string()),
    latest_invoice: types.optional(
      z.lazy(() => DtoInvoiceResponse$inboundSchema),
    ),
    line_items: types.optional(
      z.array(SubscriptionSubscriptionLineItem$inboundSchema),
    ),
    lookup_key: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), types.string())),
    overage_factor: types.optional(types.string()),
    parent_subscription_id: types.optional(types.string()),
    pause_status: types.optional(PauseStatus$inboundSchema),
    pauses: types.optional(
      z.array(SubscriptionSubscriptionPause$inboundSchema),
    ),
    payment_behavior: types.optional(types.string()),
    payment_terms: types.optional(PaymentTerms$inboundSchema),
    phases: types.optional(z.array(DtoSubscriptionPhaseResponse$inboundSchema)),
    plan: types.optional(DtoPlanResponse$inboundSchema),
    plan_id: types.optional(types.string()),
    proration_behavior: types.optional(ProrationBehavior$inboundSchema),
    start_date: types.optional(types.string()),
    status: types.optional(Status$inboundSchema),
    subscription_status: types.optional(SubscriptionStatus$inboundSchema),
    tenant_id: types.optional(types.string()),
    trial_end: types.optional(types.string()),
    trial_start: types.optional(types.string()),
    updated_at: types.optional(types.string()),
    updated_by: types.optional(types.string()),
    version: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_pause_id": "activePauseId",
      "billing_anchor": "billingAnchor",
      "billing_cadence": "billingCadence",
      "billing_cycle": "billingCycle",
      "billing_period": "billingPeriod",
      "billing_period_count": "billingPeriodCount",
      "cancel_at": "cancelAt",
      "cancel_at_period_end": "cancelAtPeriodEnd",
      "cancelled_at": "cancelledAt",
      "collection_method": "collectionMethod",
      "commitment_amount": "commitmentAmount",
      "commitment_duration": "commitmentDuration",
      "coupon_associations": "couponAssociations",
      "created_at": "createdAt",
      "created_by": "createdBy",
      "credit_grants": "creditGrants",
      "current_period_end": "currentPeriodEnd",
      "current_period_start": "currentPeriodStart",
      "customer_id": "customerId",
      "customer_timezone": "customerTimezone",
      "enable_true_up": "enableTrueUp",
      "end_date": "endDate",
      "environment_id": "environmentId",
      "gateway_payment_method_id": "gatewayPaymentMethodId",
      "invoicing_customer_id": "invoicingCustomerId",
      "latest_invoice": "latestInvoice",
      "line_items": "lineItems",
      "lookup_key": "lookupKey",
      "overage_factor": "overageFactor",
      "parent_subscription_id": "parentSubscriptionId",
      "pause_status": "pauseStatus",
      "payment_behavior": "paymentBehavior",
      "payment_terms": "paymentTerms",
      "plan_id": "planId",
      "proration_behavior": "prorationBehavior",
      "start_date": "startDate",
      "subscription_status": "subscriptionStatus",
      "tenant_id": "tenantId",
      "trial_end": "trialEnd",
      "trial_start": "trialStart",
      "updated_at": "updatedAt",
      "updated_by": "updatedBy",
    });
  }),
);

export function dtoSubscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoSubscriptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoSubscriptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoSubscriptionResponse' from JSON`,
  );
}
