/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoAggregatedEntitlement,
  DtoAggregatedEntitlement$inboundSchema,
} from "./dto-aggregated-entitlement.js";
import {
  DtoEntitlementSource,
  DtoEntitlementSource$inboundSchema,
} from "./dto-entitlement-source.js";
import {
  DtoFeatureResponse,
  DtoFeatureResponse$inboundSchema,
} from "./dto-feature-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type DtoAggregatedFeature = {
  entitlement?: DtoAggregatedEntitlement | undefined;
  feature?: DtoFeatureResponse | undefined;
  sources?: Array<DtoEntitlementSource> | undefined;
};

/** @internal */
export const DtoAggregatedFeature$inboundSchema: z.ZodMiniType<
  DtoAggregatedFeature,
  unknown
> = z.object({
  entitlement: types.optional(DtoAggregatedEntitlement$inboundSchema),
  feature: types.optional(DtoFeatureResponse$inboundSchema),
  sources: types.optional(z.array(DtoEntitlementSource$inboundSchema)),
});

export function dtoAggregatedFeatureFromJSON(
  jsonString: string,
): SafeParseResult<DtoAggregatedFeature, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoAggregatedFeature$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoAggregatedFeature' from JSON`,
  );
}
