/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { UserType, UserType$outboundSchema } from "./user-type.js";

export type DtoCreateUserRequest = {
  /**
   * Required when type is "user"
   */
  email?: string | undefined;
  /**
   * Required when type is "service_account"
   */
  roles?: Array<string> | undefined;
  type: UserType;
};

/** @internal */
export type DtoCreateUserRequest$Outbound = {
  email?: string | undefined;
  roles?: Array<string> | undefined;
  type: string;
};

/** @internal */
export const DtoCreateUserRequest$outboundSchema: z.ZodMiniType<
  DtoCreateUserRequest$Outbound,
  DtoCreateUserRequest
> = z.object({
  email: z.optional(z.string()),
  roles: z.optional(z.array(z.string())),
  type: UserType$outboundSchema,
});

export function dtoCreateUserRequestToJSON(
  dtoCreateUserRequest: DtoCreateUserRequest,
): string {
  return JSON.stringify(
    DtoCreateUserRequest$outboundSchema.parse(dtoCreateUserRequest),
  );
}
