/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoSecretResponse,
  DtoSecretResponse$inboundSchema,
} from "./dto-secret-response.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./pagination-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type DtoListSecretsResponse = {
  items?: Array<DtoSecretResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListSecretsResponse$inboundSchema: z.ZodMiniType<
  DtoListSecretsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoSecretResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function dtoListSecretsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListSecretsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListSecretsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListSecretsResponse' from JSON`,
  );
}
