/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoUserResponse,
  DtoUserResponse$inboundSchema,
} from "./dto-user-response.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./pagination-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type DtoListUsersResponse = {
  items?: Array<DtoUserResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListUsersResponse$inboundSchema: z.ZodMiniType<
  DtoListUsersResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoUserResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function dtoListUsersResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListUsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListUsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListUsersResponse' from JSON`,
  );
}
