/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CancelImmediatelyInvoicePolicy,
  CancelImmediatelyInvoicePolicy$outboundSchema,
} from "./cancel-immediately-invoice-policy.js";
import {
  CancellationType,
  CancellationType$outboundSchema,
} from "./cancellation-type.js";
import {
  ProrationBehavior,
  ProrationBehavior$outboundSchema,
} from "./proration-behavior.js";

export type DtoCancelSubscriptionRequest = {
  /**
   * CancelAt is the custom date to cancel the subscription.
   *
   * @remarks
   * Required when CancellationType is "scheduled_date". Must be in the future.
   */
  cancelAt?: string | undefined;
  cancelImmediatelyInovicePolicy?: CancelImmediatelyInvoicePolicy | undefined;
  cancellationType: CancellationType;
  prorationBehavior?: ProrationBehavior | undefined;
  /**
   * Reason for cancellation (for audit and business intelligence)
   */
  reason?: string | undefined;
};

/** @internal */
export type DtoCancelSubscriptionRequest$Outbound = {
  cancel_at?: string | undefined;
  cancel_immediately_inovice_policy?: string | undefined;
  cancellation_type: string;
  proration_behavior?: string | undefined;
  reason?: string | undefined;
};

/** @internal */
export const DtoCancelSubscriptionRequest$outboundSchema: z.ZodMiniType<
  DtoCancelSubscriptionRequest$Outbound,
  DtoCancelSubscriptionRequest
> = z.pipe(
  z.object({
    cancelAt: z.optional(z.string()),
    cancelImmediatelyInovicePolicy: z.optional(
      CancelImmediatelyInvoicePolicy$outboundSchema,
    ),
    cancellationType: CancellationType$outboundSchema,
    prorationBehavior: z.optional(ProrationBehavior$outboundSchema),
    reason: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cancelAt: "cancel_at",
      cancelImmediatelyInovicePolicy: "cancel_immediately_inovice_policy",
      cancellationType: "cancellation_type",
      prorationBehavior: "proration_behavior",
    });
  }),
);

export function dtoCancelSubscriptionRequestToJSON(
  dtoCancelSubscriptionRequest: DtoCancelSubscriptionRequest,
): string {
  return JSON.stringify(
    DtoCancelSubscriptionRequest$outboundSchema.parse(
      dtoCancelSubscriptionRequest,
    ),
  );
}
