/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  EntitlementEntityType,
  EntitlementEntityType$outboundSchema,
} from "./entitlement-entity-type.js";
import {
  EntitlementUsageResetPeriod,
  EntitlementUsageResetPeriod$outboundSchema,
} from "./entitlement-usage-reset-period.js";
import { FeatureType, FeatureType$outboundSchema } from "./feature-type.js";

export type DtoCreateEntitlementRequest = {
  endDate?: string | undefined;
  entityId?: string | undefined;
  entityType?: EntitlementEntityType | undefined;
  featureId: string;
  featureType: FeatureType;
  isEnabled?: boolean | undefined;
  isSoftLimit?: boolean | undefined;
  parentEntitlementId?: string | undefined;
  planId?: string | undefined;
  startDate?: string | undefined;
  staticValue?: string | undefined;
  usageLimit?: number | undefined;
  usageResetPeriod?: EntitlementUsageResetPeriod | undefined;
};

/** @internal */
export type DtoCreateEntitlementRequest$Outbound = {
  end_date?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: string | undefined;
  feature_id: string;
  feature_type: string;
  is_enabled?: boolean | undefined;
  is_soft_limit?: boolean | undefined;
  parent_entitlement_id?: string | undefined;
  plan_id?: string | undefined;
  start_date?: string | undefined;
  static_value?: string | undefined;
  usage_limit?: number | undefined;
  usage_reset_period?: string | undefined;
};

/** @internal */
export const DtoCreateEntitlementRequest$outboundSchema: z.ZodMiniType<
  DtoCreateEntitlementRequest$Outbound,
  DtoCreateEntitlementRequest
> = z.pipe(
  z.object({
    endDate: z.optional(z.string()),
    entityId: z.optional(z.string()),
    entityType: z.optional(EntitlementEntityType$outboundSchema),
    featureId: z.string(),
    featureType: FeatureType$outboundSchema,
    isEnabled: z.optional(z.boolean()),
    isSoftLimit: z.optional(z.boolean()),
    parentEntitlementId: z.optional(z.string()),
    planId: z.optional(z.string()),
    startDate: z.optional(z.string()),
    staticValue: z.optional(z.string()),
    usageLimit: z.optional(z.int()),
    usageResetPeriod: z.optional(EntitlementUsageResetPeriod$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      endDate: "end_date",
      entityId: "entity_id",
      entityType: "entity_type",
      featureId: "feature_id",
      featureType: "feature_type",
      isEnabled: "is_enabled",
      isSoftLimit: "is_soft_limit",
      parentEntitlementId: "parent_entitlement_id",
      planId: "plan_id",
      startDate: "start_date",
      staticValue: "static_value",
      usageLimit: "usage_limit",
      usageResetPeriod: "usage_reset_period",
    });
  }),
);

export function dtoCreateEntitlementRequestToJSON(
  dtoCreateEntitlementRequest: DtoCreateEntitlementRequest,
): string {
  return JSON.stringify(
    DtoCreateEntitlementRequest$outboundSchema.parse(
      dtoCreateEntitlementRequest,
    ),
  );
}
