/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  ScheduleStatus,
  ScheduleStatus$inboundSchema,
} from "./schedule-status.js";
import { SDKValidationError } from "./sdk-validation-error.js";

/**
 * Confirmation of schedule cancellation
 */
export type DtoCancelScheduleResponse = {
  /**
   * message is a confirmation message
   */
  message?: string | undefined;
  status?: ScheduleStatus | undefined;
};

/** @internal */
export const DtoCancelScheduleResponse$inboundSchema: z.ZodMiniType<
  DtoCancelScheduleResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  status: types.optional(ScheduleStatus$inboundSchema),
});

export function dtoCancelScheduleResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoCancelScheduleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoCancelScheduleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoCancelScheduleResponse' from JSON`,
  );
}
