/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  AggregationType,
  AggregationType$inboundSchema,
} from "./aggregation-type.js";
import {
  CommitmentInfo,
  CommitmentInfo$inboundSchema,
} from "./commitment-info.js";
import {
  DtoPriceResponse,
  DtoPriceResponse$inboundSchema,
} from "./dto-price-response.js";
import {
  DtoUsageAnalyticPoint,
  DtoUsageAnalyticPoint$inboundSchema,
} from "./dto-usage-analytic-point.js";
import {
  GithubComFlexpriceFlexpriceInternalDomainAddonAddon,
  GithubComFlexpriceFlexpriceInternalDomainAddonAddon$inboundSchema,
} from "./github-com-flexprice-flexprice-internal-domain-addon-addon.js";
import {
  GithubComFlexpriceFlexpriceInternalDomainFeatureFeature,
  GithubComFlexpriceFlexpriceInternalDomainFeatureFeature$inboundSchema,
} from "./github-com-flexprice-flexprice-internal-domain-feature-feature.js";
import {
  GithubComFlexpriceFlexpriceInternalDomainPlanPlan,
  GithubComFlexpriceFlexpriceInternalDomainPlanPlan$inboundSchema,
} from "./github-com-flexprice-flexprice-internal-domain-plan-plan.js";
import { MeterMeter, MeterMeter$inboundSchema } from "./meter-meter.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  SubscriptionSubscriptionLineItem,
  SubscriptionSubscriptionLineItem$inboundSchema,
} from "./subscription-subscription-line-item.js";
import { WindowSize, WindowSize$inboundSchema } from "./window-size.js";

export type DtoUsageAnalyticItem = {
  addOnId?: string | undefined;
  addon?: GithubComFlexpriceFlexpriceInternalDomainAddonAddon | undefined;
  aggregationType?: AggregationType | undefined;
  commitmentInfo?: CommitmentInfo | undefined;
  currency?: string | undefined;
  /**
   * Number of events that contributed to this aggregation
   */
  eventCount?: number | undefined;
  eventName?: string | undefined;
  feature?: GithubComFlexpriceFlexpriceInternalDomainFeatureFeature | undefined;
  featureId?: string | undefined;
  meter?: MeterMeter | undefined;
  /**
   * Meter ID
   */
  meterId?: string | undefined;
  name?: string | undefined;
  plan?: GithubComFlexpriceFlexpriceInternalDomainPlanPlan | undefined;
  planId?: string | undefined;
  points?: Array<DtoUsageAnalyticPoint> | undefined;
  price?: DtoPriceResponse | undefined;
  /**
   * Price ID used for this usage
   */
  priceId?: string | undefined;
  /**
   * Stores property values for flexible grouping (e.g., org_id -> "org123")
   */
  properties?: { [k: string]: string } | undefined;
  source?: string | undefined;
  /**
   * List of sources when not grouping by source
   */
  sources?: Array<string> | undefined;
  /**
   * Subscription line item ID
   */
  subLineItemId?: string | undefined;
  /**
   * Subscription ID
   */
  subscriptionId?: string | undefined;
  subscriptionLineItem?: SubscriptionSubscriptionLineItem | undefined;
  totalCost?: string | undefined;
  totalUsage?: string | undefined;
  unit?: string | undefined;
  unitPlural?: string | undefined;
  windowSize?: WindowSize | undefined;
};

/** @internal */
export const DtoUsageAnalyticItem$inboundSchema: z.ZodMiniType<
  DtoUsageAnalyticItem,
  unknown
> = z.pipe(
  z.object({
    add_on_id: types.optional(types.string()),
    addon: types.optional(
      GithubComFlexpriceFlexpriceInternalDomainAddonAddon$inboundSchema,
    ),
    aggregation_type: types.optional(AggregationType$inboundSchema),
    commitment_info: types.optional(CommitmentInfo$inboundSchema),
    currency: types.optional(types.string()),
    event_count: types.optional(types.number()),
    event_name: types.optional(types.string()),
    feature: types.optional(
      GithubComFlexpriceFlexpriceInternalDomainFeatureFeature$inboundSchema,
    ),
    feature_id: types.optional(types.string()),
    meter: types.optional(MeterMeter$inboundSchema),
    meter_id: types.optional(types.string()),
    name: types.optional(types.string()),
    plan: types.optional(
      GithubComFlexpriceFlexpriceInternalDomainPlanPlan$inboundSchema,
    ),
    plan_id: types.optional(types.string()),
    points: types.optional(z.array(DtoUsageAnalyticPoint$inboundSchema)),
    price: types.optional(DtoPriceResponse$inboundSchema),
    price_id: types.optional(types.string()),
    properties: types.optional(z.record(z.string(), types.string())),
    source: types.optional(types.string()),
    sources: types.optional(z.array(types.string())),
    sub_line_item_id: types.optional(types.string()),
    subscription_id: types.optional(types.string()),
    subscription_line_item: types.optional(
      SubscriptionSubscriptionLineItem$inboundSchema,
    ),
    total_cost: types.optional(types.string()),
    total_usage: types.optional(types.string()),
    unit: types.optional(types.string()),
    unit_plural: types.optional(types.string()),
    window_size: types.optional(WindowSize$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "add_on_id": "addOnId",
      "aggregation_type": "aggregationType",
      "commitment_info": "commitmentInfo",
      "event_count": "eventCount",
      "event_name": "eventName",
      "feature_id": "featureId",
      "meter_id": "meterId",
      "plan_id": "planId",
      "price_id": "priceId",
      "sub_line_item_id": "subLineItemId",
      "subscription_id": "subscriptionId",
      "subscription_line_item": "subscriptionLineItem",
      "total_cost": "totalCost",
      "total_usage": "totalUsage",
      "unit_plural": "unitPlural",
      "window_size": "windowSize",
    });
  }),
);

export function dtoUsageAnalyticItemFromJSON(
  jsonString: string,
): SafeParseResult<DtoUsageAnalyticItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoUsageAnalyticItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoUsageAnalyticItem' from JSON`,
  );
}
