/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DtoDeleteCreditGrantRequest = {
  /**
   * EffectiveDate is optional; when set (subscription scope) the grant end date is set to this time.
   */
  effectiveDate?: string | undefined;
};

/** @internal */
export type DtoDeleteCreditGrantRequest$Outbound = {
  effective_date?: string | undefined;
};

/** @internal */
export const DtoDeleteCreditGrantRequest$outboundSchema: z.ZodMiniType<
  DtoDeleteCreditGrantRequest$Outbound,
  DtoDeleteCreditGrantRequest
> = z.pipe(
  z.object({
    effectiveDate: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      effectiveDate: "effective_date",
    });
  }),
);

export function dtoDeleteCreditGrantRequestToJSON(
  dtoDeleteCreditGrantRequest: DtoDeleteCreditGrantRequest,
): string {
  return JSON.stringify(
    DtoDeleteCreditGrantRequest$outboundSchema.parse(
      dtoDeleteCreditGrantRequest,
    ),
  );
}
