/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoEventCostInfo,
  DtoEventCostInfo$inboundSchema,
} from "./dto-event-cost-info.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type DtoGetHuggingFaceBillingDataResponse = {
  requests?: Array<DtoEventCostInfo> | undefined;
};

/** @internal */
export const DtoGetHuggingFaceBillingDataResponse$inboundSchema: z.ZodMiniType<
  DtoGetHuggingFaceBillingDataResponse,
  unknown
> = z.object({
  requests: types.optional(z.array(DtoEventCostInfo$inboundSchema)),
});

export function dtoGetHuggingFaceBillingDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoGetHuggingFaceBillingDataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DtoGetHuggingFaceBillingDataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoGetHuggingFaceBillingDataResponse' from JSON`,
  );
}
