/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoTenantResponse,
  DtoTenantResponse$inboundSchema,
} from "./dto-tenant-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import { UserType, UserType$inboundSchema } from "./user-type.js";

export type DtoCreateUserResponse = {
  /**
   * Empty for service accounts
   */
  email?: string | undefined;
  id?: string | undefined;
  password?: string | undefined;
  roles?: Array<string> | undefined;
  tenant?: DtoTenantResponse | undefined;
  type?: UserType | undefined;
};

/** @internal */
export const DtoCreateUserResponse$inboundSchema: z.ZodMiniType<
  DtoCreateUserResponse,
  unknown
> = z.object({
  email: types.optional(types.string()),
  id: types.optional(types.string()),
  password: types.optional(types.string()),
  roles: types.optional(z.array(types.string())),
  tenant: types.optional(DtoTenantResponse$inboundSchema),
  type: types.optional(UserType$inboundSchema),
});

export function dtoCreateUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoCreateUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoCreateUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoCreateUserResponse' from JSON`,
  );
}
