/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { EntityType, EntityType$outboundSchema } from "./entity-type.js";
import { FileType, FileType$outboundSchema } from "./file-type.js";
import { TaskType, TaskType$outboundSchema } from "./task-type.js";

export type DtoCreateTaskRequest = {
  entityType: EntityType;
  fileName?: string | undefined;
  fileType: FileType;
  fileUrl: string;
  metadata?: { [k: string]: any } | undefined;
  taskType: TaskType;
};

/** @internal */
export type DtoCreateTaskRequest$Outbound = {
  entity_type: string;
  file_name?: string | undefined;
  file_type: string;
  file_url: string;
  metadata?: { [k: string]: any } | undefined;
  task_type: string;
};

/** @internal */
export const DtoCreateTaskRequest$outboundSchema: z.ZodMiniType<
  DtoCreateTaskRequest$Outbound,
  DtoCreateTaskRequest
> = z.pipe(
  z.object({
    entityType: EntityType$outboundSchema,
    fileName: z.optional(z.string()),
    fileType: FileType$outboundSchema,
    fileUrl: z.string(),
    metadata: z.optional(z.record(z.string(), z.any())),
    taskType: TaskType$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      entityType: "entity_type",
      fileName: "file_name",
      fileType: "file_type",
      fileUrl: "file_url",
      taskType: "task_type",
    });
  }),
);

export function dtoCreateTaskRequestToJSON(
  dtoCreateTaskRequest: DtoCreateTaskRequest,
): string {
  return JSON.stringify(
    DtoCreateTaskRequest$outboundSchema.parse(dtoCreateTaskRequest),
  );
}
