/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoTaxRateResponse,
  DtoTaxRateResponse$inboundSchema,
} from "./dto-tax-rate-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import { Status, Status$inboundSchema } from "./status.js";
import {
  TaxRateEntityType,
  TaxRateEntityType$inboundSchema,
} from "./tax-rate-entity-type.js";

export type DtoTaxAssociationResponse = {
  /**
   * Whether this tax should be automatically applied
   */
  autoApply?: boolean | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  /**
   * Currency
   */
  currency?: string | undefined;
  /**
   * ID of the entity this tax rate applies to
   */
  entityId?: string | undefined;
  entityType?: TaxRateEntityType | undefined;
  /**
   * EnvironmentID is the ID of the environment this tax rate config belongs to
   */
  environmentId?: string | undefined;
  /**
   * ID of the ent.
   */
  id?: string | undefined;
  /**
   * Metadata holds the value of the "metadata" field.
   */
  metadata?: { [k: string]: string } | undefined;
  /**
   * Priority for tax resolution (lower number = higher priority)
   */
  priority?: number | undefined;
  status?: Status | undefined;
  taxRate?: DtoTaxRateResponse | undefined;
  /**
   * Reference to the TaxRate entity
   */
  taxRateId?: string | undefined;
  tenantId?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const DtoTaxAssociationResponse$inboundSchema: z.ZodMiniType<
  DtoTaxAssociationResponse,
  unknown
> = z.pipe(
  z.object({
    auto_apply: types.optional(types.boolean()),
    created_at: types.optional(types.string()),
    created_by: types.optional(types.string()),
    currency: types.optional(types.string()),
    entity_id: types.optional(types.string()),
    entity_type: types.optional(TaxRateEntityType$inboundSchema),
    environment_id: types.optional(types.string()),
    id: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), types.string())),
    priority: types.optional(types.number()),
    status: types.optional(Status$inboundSchema),
    tax_rate: types.optional(DtoTaxRateResponse$inboundSchema),
    tax_rate_id: types.optional(types.string()),
    tenant_id: types.optional(types.string()),
    updated_at: types.optional(types.string()),
    updated_by: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "auto_apply": "autoApply",
      "created_at": "createdAt",
      "created_by": "createdBy",
      "entity_id": "entityId",
      "entity_type": "entityType",
      "environment_id": "environmentId",
      "tax_rate": "taxRate",
      "tax_rate_id": "taxRateId",
      "tenant_id": "tenantId",
      "updated_at": "updatedAt",
      "updated_by": "updatedBy",
    });
  }),
);

export function dtoTaxAssociationResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoTaxAssociationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoTaxAssociationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoTaxAssociationResponse' from JSON`,
  );
}
