/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  AlertSettings,
  AlertSettings$Outbound,
  AlertSettings$outboundSchema,
} from "./alert-settings.js";
import {
  MeterFilter,
  MeterFilter$Outbound,
  MeterFilter$outboundSchema,
} from "./meter-filter.js";

export type DtoUpdateFeatureRequest = {
  alertSettings?: AlertSettings | undefined;
  description?: string | undefined;
  filters?: Array<MeterFilter> | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  unitPlural?: string | undefined;
  unitSingular?: string | undefined;
};

/** @internal */
export type DtoUpdateFeatureRequest$Outbound = {
  alert_settings?: AlertSettings$Outbound | undefined;
  description?: string | undefined;
  filters?: Array<MeterFilter$Outbound> | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  unit_plural?: string | undefined;
  unit_singular?: string | undefined;
};

/** @internal */
export const DtoUpdateFeatureRequest$outboundSchema: z.ZodMiniType<
  DtoUpdateFeatureRequest$Outbound,
  DtoUpdateFeatureRequest
> = z.pipe(
  z.object({
    alertSettings: z.optional(AlertSettings$outboundSchema),
    description: z.optional(z.string()),
    filters: z.optional(z.array(MeterFilter$outboundSchema)),
    metadata: z.optional(z.record(z.string(), z.string())),
    name: z.optional(z.string()),
    unitPlural: z.optional(z.string()),
    unitSingular: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      alertSettings: "alert_settings",
      unitPlural: "unit_plural",
      unitSingular: "unit_singular",
    });
  }),
);

export function dtoUpdateFeatureRequestToJSON(
  dtoUpdateFeatureRequest: DtoUpdateFeatureRequest,
): string {
  return JSON.stringify(
    DtoUpdateFeatureRequest$outboundSchema.parse(dtoUpdateFeatureRequest),
  );
}
