/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$inboundSchema,
} from "./dto-credit-grant-response.js";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$inboundSchema,
} from "./dto-invoice-response.js";
import {
  DtoProrationDetails,
  DtoProrationDetails$inboundSchema,
} from "./dto-proration-details.js";
import {
  DtoSubscriptionSummary,
  DtoSubscriptionSummary$inboundSchema,
} from "./dto-subscription-summary.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  SubscriptionChangeType,
  SubscriptionChangeType$inboundSchema,
} from "./subscription-change-type.js";

/**
 * Response after successfully executing a subscription plan change
 */
export type DtoSubscriptionChangeExecuteResponse = {
  changeType?: SubscriptionChangeType | undefined;
  /**
   * credit_grants contains any credit grants created for proration credits
   */
  creditGrants?: Array<DtoCreditGrantResponse> | undefined;
  /**
   * effective_date is when the change took effect
   */
  effectiveDate?: string | undefined;
  invoice?: DtoInvoiceResponse | undefined;
  /**
   * is_scheduled indicates if the change was scheduled or executed immediately
   */
  isScheduled?: boolean | undefined;
  /**
   * metadata from the request
   */
  metadata?: { [k: string]: string } | undefined;
  newSubscription?: DtoSubscriptionSummary | undefined;
  oldSubscription?: DtoSubscriptionSummary | undefined;
  prorationApplied?: DtoProrationDetails | undefined;
  /**
   * schedule_id is the ID of the created schedule (only if is_scheduled=true)
   */
  scheduleId?: string | undefined;
  /**
   * scheduled_at is when the change will execute (only if is_scheduled=true)
   */
  scheduledAt?: string | undefined;
};

/** @internal */
export const DtoSubscriptionChangeExecuteResponse$inboundSchema: z.ZodMiniType<
  DtoSubscriptionChangeExecuteResponse,
  unknown
> = z.pipe(
  z.object({
    change_type: types.optional(SubscriptionChangeType$inboundSchema),
    credit_grants: types.optional(
      z.array(DtoCreditGrantResponse$inboundSchema),
    ),
    effective_date: types.optional(types.string()),
    invoice: types.optional(DtoInvoiceResponse$inboundSchema),
    is_scheduled: types.optional(types.boolean()),
    metadata: types.optional(z.record(z.string(), types.string())),
    new_subscription: types.optional(DtoSubscriptionSummary$inboundSchema),
    old_subscription: types.optional(DtoSubscriptionSummary$inboundSchema),
    proration_applied: types.optional(DtoProrationDetails$inboundSchema),
    schedule_id: types.optional(types.string()),
    scheduled_at: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "change_type": "changeType",
      "credit_grants": "creditGrants",
      "effective_date": "effectiveDate",
      "is_scheduled": "isScheduled",
      "new_subscription": "newSubscription",
      "old_subscription": "oldSubscription",
      "proration_applied": "prorationApplied",
      "schedule_id": "scheduleId",
      "scheduled_at": "scheduledAt",
    });
  }),
);

export function dtoSubscriptionChangeExecuteResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoSubscriptionChangeExecuteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DtoSubscriptionChangeExecuteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoSubscriptionChangeExecuteResponse' from JSON`,
  );
}
