/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  BillingCadence,
  BillingCadence$outboundSchema,
} from "./billing-cadence.js";
import { BillingCycle, BillingCycle$outboundSchema } from "./billing-cycle.js";
import {
  BillingPeriod,
  BillingPeriod$outboundSchema,
} from "./billing-period.js";
import {
  CollectionMethod,
  CollectionMethod$outboundSchema,
} from "./collection-method.js";
import {
  DtoAddAddonToSubscriptionRequest,
  DtoAddAddonToSubscriptionRequest$Outbound,
  DtoAddAddonToSubscriptionRequest$outboundSchema,
} from "./dto-add-addon-to-subscription-request.js";
import {
  DtoCreateCreditGrantRequest,
  DtoCreateCreditGrantRequest$Outbound,
  DtoCreateCreditGrantRequest$outboundSchema,
} from "./dto-create-credit-grant-request.js";
import {
  DtoCreateSubscriptionLineItemRequest,
  DtoCreateSubscriptionLineItemRequest$Outbound,
  DtoCreateSubscriptionLineItemRequest$outboundSchema,
} from "./dto-create-subscription-line-item-request.js";
import {
  DtoLineItemCommitmentConfig,
  DtoLineItemCommitmentConfig$Outbound,
  DtoLineItemCommitmentConfig$outboundSchema,
} from "./dto-line-item-commitment-config.js";
import {
  DtoOverrideEntitlementRequest,
  DtoOverrideEntitlementRequest$Outbound,
  DtoOverrideEntitlementRequest$outboundSchema,
} from "./dto-override-entitlement-request.js";
import {
  DtoOverrideLineItemRequest,
  DtoOverrideLineItemRequest$Outbound,
  DtoOverrideLineItemRequest$outboundSchema,
} from "./dto-override-line-item-request.js";
import {
  DtoSubscriptionPhaseCreateRequest,
  DtoSubscriptionPhaseCreateRequest$Outbound,
  DtoSubscriptionPhaseCreateRequest$outboundSchema,
} from "./dto-subscription-phase-create-request.js";
import {
  DtoTaxRateOverride,
  DtoTaxRateOverride$Outbound,
  DtoTaxRateOverride$outboundSchema,
} from "./dto-tax-rate-override.js";
import {
  InvoiceBilling,
  InvoiceBilling$outboundSchema,
} from "./invoice-billing.js";
import {
  PaymentBehavior,
  PaymentBehavior$outboundSchema,
} from "./payment-behavior.js";
import { PaymentTerms, PaymentTerms$outboundSchema } from "./payment-terms.js";
import {
  ProrationBehavior,
  ProrationBehavior$outboundSchema,
} from "./proration-behavior.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$outboundSchema,
} from "./subscription-status.js";

export type DtoCreateSubscriptionRequest = {
  /**
   * Addons represents addons to be added to the subscription during creation
   */
  addons?: Array<DtoAddAddonToSubscriptionRequest> | undefined;
  billingCadence: BillingCadence;
  billingCycle?: BillingCycle | undefined;
  billingPeriod: BillingPeriod;
  billingPeriodCount?: number | undefined;
  collectionMethod?: CollectionMethod | undefined;
  /**
   * CommitmentAmount is the minimum amount a customer commits to paying for a billing period
   */
  commitmentAmount?: string | undefined;
  commitmentDuration?: BillingPeriod | undefined;
  coupons?: Array<string> | undefined;
  /**
   * Credit grants to be applied when subscription is created
   */
  creditGrants?: Array<DtoCreateCreditGrantRequest> | undefined;
  currency: string;
  /**
   * customer_id is the flexprice customer id
   *
   * @remarks
   * and it is prioritized over external_customer_id in case both are provided.
   */
  customerId?: string | undefined;
  /**
   * Timezone of the customer.
   *
   * @remarks
   * If not set, the default value is UTC.
   */
  customerTimezone?: string | undefined;
  /**
   * Enable Commitment True Up Fee
   */
  enableTrueUp?: boolean | undefined;
  endDate?: string | undefined;
  /**
   * external_customer_id is the customer id in your DB
   *
   * @remarks
   * and must be same as what you provided as external_id while creating the customer in flexprice.
   */
  externalCustomerId?: string | undefined;
  gatewayPaymentMethodId?: string | undefined;
  invoiceBilling?: InvoiceBilling | undefined;
  /**
   * LineItemCommitments allows setting commitment configuration per line item (keyed by price_id)
   */
  lineItemCommitments?:
    | { [k: string]: DtoLineItemCommitmentConfig }
    | undefined;
  lineItemCoupons?: { [k: string]: Array<string> } | undefined;
  /**
   * LineItems are extra line items to add at creation (each with price_id or price), in addition to plan prices
   */
  lineItems?: Array<DtoCreateSubscriptionLineItemRequest> | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  /**
   * OverageFactor is a multiplier applied to usage beyond the commitment amount
   */
  overageFactor?: string | undefined;
  /**
   * OverrideEntitlements allows customizing specific entitlements for this subscription
   */
  overrideEntitlements?: Array<DtoOverrideEntitlementRequest> | undefined;
  /**
   * OverrideLineItems allows customizing specific prices for this subscription
   */
  overrideLineItems?: Array<DtoOverrideLineItemRequest> | undefined;
  /**
   * ParentSubscriptionID is the parent subscription ID for hierarchy (e.g. child subscription under a parent)
   */
  parentSubscriptionId?: string | undefined;
  paymentBehavior?: PaymentBehavior | undefined;
  paymentTerms?: PaymentTerms | undefined;
  /**
   * Phases represents subscription phases to be created with the subscription
   */
  phases?: Array<DtoSubscriptionPhaseCreateRequest> | undefined;
  planId: string;
  prorationBehavior?: ProrationBehavior | undefined;
  startDate?: string | undefined;
  subscriptionStatus?: SubscriptionStatus | undefined;
  /**
   * tax_rate_overrides is the tax rate overrides	to be applied to the subscription
   */
  taxRateOverrides?: Array<DtoTaxRateOverride> | undefined;
  trialEnd?: string | undefined;
  trialStart?: string | undefined;
};

/** @internal */
export type DtoCreateSubscriptionRequest$Outbound = {
  addons?: Array<DtoAddAddonToSubscriptionRequest$Outbound> | undefined;
  billing_cadence: string;
  billing_cycle?: string | undefined;
  billing_period: string;
  billing_period_count?: number | undefined;
  collection_method?: string | undefined;
  commitment_amount?: string | undefined;
  commitment_duration?: string | undefined;
  coupons?: Array<string> | undefined;
  credit_grants?: Array<DtoCreateCreditGrantRequest$Outbound> | undefined;
  currency: string;
  customer_id?: string | undefined;
  customer_timezone?: string | undefined;
  enable_true_up?: boolean | undefined;
  end_date?: string | undefined;
  external_customer_id?: string | undefined;
  gateway_payment_method_id?: string | undefined;
  invoice_billing?: string | undefined;
  line_item_commitments?:
    | { [k: string]: DtoLineItemCommitmentConfig$Outbound }
    | undefined;
  line_item_coupons?: { [k: string]: Array<string> } | undefined;
  line_items?: Array<DtoCreateSubscriptionLineItemRequest$Outbound> | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  overage_factor?: string | undefined;
  override_entitlements?:
    | Array<DtoOverrideEntitlementRequest$Outbound>
    | undefined;
  override_line_items?: Array<DtoOverrideLineItemRequest$Outbound> | undefined;
  parent_subscription_id?: string | undefined;
  payment_behavior?: string | undefined;
  payment_terms?: string | undefined;
  phases?: Array<DtoSubscriptionPhaseCreateRequest$Outbound> | undefined;
  plan_id: string;
  proration_behavior?: string | undefined;
  start_date?: string | undefined;
  subscription_status?: string | undefined;
  tax_rate_overrides?: Array<DtoTaxRateOverride$Outbound> | undefined;
  trial_end?: string | undefined;
  trial_start?: string | undefined;
};

/** @internal */
export const DtoCreateSubscriptionRequest$outboundSchema: z.ZodMiniType<
  DtoCreateSubscriptionRequest$Outbound,
  DtoCreateSubscriptionRequest
> = z.pipe(
  z.object({
    addons: z.optional(
      z.array(DtoAddAddonToSubscriptionRequest$outboundSchema),
    ),
    billingCadence: BillingCadence$outboundSchema,
    billingCycle: z.optional(BillingCycle$outboundSchema),
    billingPeriod: BillingPeriod$outboundSchema,
    billingPeriodCount: z.optional(z.int()),
    collectionMethod: z.optional(CollectionMethod$outboundSchema),
    commitmentAmount: z.optional(z.string()),
    commitmentDuration: z.optional(BillingPeriod$outboundSchema),
    coupons: z.optional(z.array(z.string())),
    creditGrants: z.optional(
      z.array(DtoCreateCreditGrantRequest$outboundSchema),
    ),
    currency: z.string(),
    customerId: z.optional(z.string()),
    customerTimezone: z.optional(z.string()),
    enableTrueUp: z.optional(z.boolean()),
    endDate: z.optional(z.string()),
    externalCustomerId: z.optional(z.string()),
    gatewayPaymentMethodId: z.optional(z.string()),
    invoiceBilling: z.optional(InvoiceBilling$outboundSchema),
    lineItemCommitments: z.optional(
      z.record(z.string(), DtoLineItemCommitmentConfig$outboundSchema),
    ),
    lineItemCoupons: z.optional(z.record(z.string(), z.array(z.string()))),
    lineItems: z.optional(
      z.array(DtoCreateSubscriptionLineItemRequest$outboundSchema),
    ),
    lookupKey: z.optional(z.string()),
    metadata: z.optional(z.record(z.string(), z.string())),
    overageFactor: z.optional(z.string()),
    overrideEntitlements: z.optional(
      z.array(DtoOverrideEntitlementRequest$outboundSchema),
    ),
    overrideLineItems: z.optional(
      z.array(DtoOverrideLineItemRequest$outboundSchema),
    ),
    parentSubscriptionId: z.optional(z.string()),
    paymentBehavior: z.optional(PaymentBehavior$outboundSchema),
    paymentTerms: z.optional(PaymentTerms$outboundSchema),
    phases: z.optional(
      z.array(DtoSubscriptionPhaseCreateRequest$outboundSchema),
    ),
    planId: z.string(),
    prorationBehavior: z.optional(ProrationBehavior$outboundSchema),
    startDate: z.optional(z.string()),
    subscriptionStatus: z.optional(SubscriptionStatus$outboundSchema),
    taxRateOverrides: z.optional(z.array(DtoTaxRateOverride$outboundSchema)),
    trialEnd: z.optional(z.string()),
    trialStart: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      billingCadence: "billing_cadence",
      billingCycle: "billing_cycle",
      billingPeriod: "billing_period",
      billingPeriodCount: "billing_period_count",
      collectionMethod: "collection_method",
      commitmentAmount: "commitment_amount",
      commitmentDuration: "commitment_duration",
      creditGrants: "credit_grants",
      customerId: "customer_id",
      customerTimezone: "customer_timezone",
      enableTrueUp: "enable_true_up",
      endDate: "end_date",
      externalCustomerId: "external_customer_id",
      gatewayPaymentMethodId: "gateway_payment_method_id",
      invoiceBilling: "invoice_billing",
      lineItemCommitments: "line_item_commitments",
      lineItemCoupons: "line_item_coupons",
      lineItems: "line_items",
      lookupKey: "lookup_key",
      overageFactor: "overage_factor",
      overrideEntitlements: "override_entitlements",
      overrideLineItems: "override_line_items",
      parentSubscriptionId: "parent_subscription_id",
      paymentBehavior: "payment_behavior",
      paymentTerms: "payment_terms",
      planId: "plan_id",
      prorationBehavior: "proration_behavior",
      startDate: "start_date",
      subscriptionStatus: "subscription_status",
      taxRateOverrides: "tax_rate_overrides",
      trialEnd: "trial_end",
      trialStart: "trial_start",
    });
  }),
);

export function dtoCreateSubscriptionRequestToJSON(
  dtoCreateSubscriptionRequest: DtoCreateSubscriptionRequest,
): string {
  return JSON.stringify(
    DtoCreateSubscriptionRequest$outboundSchema.parse(
      dtoCreateSubscriptionRequest,
    ),
  );
}
