/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  DtoCreateInvoiceLineItemRequest,
  DtoCreateInvoiceLineItemRequest$Outbound,
  DtoCreateInvoiceLineItemRequest$outboundSchema,
} from "./dto-create-invoice-line-item-request.js";
import {
  DtoInvoiceCoupon,
  DtoInvoiceCoupon$Outbound,
  DtoInvoiceCoupon$outboundSchema,
} from "./dto-invoice-coupon.js";
import {
  DtoInvoiceLineItemCoupon,
  DtoInvoiceLineItemCoupon$Outbound,
  DtoInvoiceLineItemCoupon$outboundSchema,
} from "./dto-invoice-line-item-coupon.js";
import {
  DtoTaxRateOverride,
  DtoTaxRateOverride$Outbound,
  DtoTaxRateOverride$outboundSchema,
} from "./dto-tax-rate-override.js";
import {
  DtoTaxRateResponse,
  DtoTaxRateResponse$Outbound,
  DtoTaxRateResponse$outboundSchema,
} from "./dto-tax-rate-response.js";
import {
  InvoiceBillingReason,
  InvoiceBillingReason$outboundSchema,
} from "./invoice-billing-reason.js";
import {
  InvoiceStatus,
  InvoiceStatus$outboundSchema,
} from "./invoice-status.js";
import { InvoiceType, InvoiceType$outboundSchema } from "./invoice-type.js";
import {
  PaymentStatus,
  PaymentStatus$outboundSchema,
} from "./payment-status.js";

export type DtoCreateInvoiceRequest = {
  /**
   * amount_due is the total amount that needs to be paid for this invoice
   */
  amountDue: string;
  /**
   * amount_paid is the amount that has been paid towards this invoice
   */
  amountPaid?: string | undefined;
  /**
   * billing_period is the period this invoice covers (e.g., "monthly", "yearly")
   */
  billingPeriod?: string | undefined;
  billingReason?: InvoiceBillingReason | undefined;
  /**
   * coupons
   */
  coupons?: Array<string> | undefined;
  /**
   * currency is the three-letter ISO currency code (e.g., USD, EUR) for the invoice
   */
  currency: string;
  /**
   * customer_id is the unique identifier of the customer this invoice belongs to
   */
  customerId: string;
  /**
   * description is an optional text description of the invoice
   */
  description?: string | undefined;
  /**
   * due_date is the date by which payment is expected
   */
  dueDate?: string | undefined;
  /**
   * idempotency_key is an optional key used to prevent duplicate invoice creation
   */
  idempotencyKey?: string | undefined;
  /**
   * Invoice Coupons
   */
  invoiceCoupons?: Array<DtoInvoiceCoupon> | undefined;
  /**
   * invoice_number is an optional human-readable identifier for the invoice
   */
  invoiceNumber?: string | undefined;
  /**
   * invoice_pdf_url is the URL where customers can download the PDF version of this invoice
   */
  invoicePdfUrl?: string | undefined;
  invoiceStatus?: InvoiceStatus | undefined;
  invoiceType?: InvoiceType | undefined;
  /**
   * Invoice Line Item Coupons
   */
  lineItemCoupons?: Array<DtoInvoiceLineItemCoupon> | undefined;
  /**
   * line_items contains the individual items that make up this invoice
   */
  lineItems?: Array<DtoCreateInvoiceLineItemRequest> | undefined;
  metadata?: { [k: string]: string } | undefined;
  paymentStatus?: PaymentStatus | undefined;
  /**
   * period_end is the end date of the billing period
   */
  periodEnd?: string | undefined;
  /**
   * period_start is the start date of the billing period
   */
  periodStart?: string | undefined;
  /**
   * prepared_tax_rates contains the tax rates pre-resolved by the caller (e.g., billing service)
   */
  preparedTaxRates?: Array<DtoTaxRateResponse> | undefined;
  /**
   * subscription_id is the optional unique identifier of the subscription associated with this invoice
   */
  subscriptionId?: string | undefined;
  /**
   * subtotal is the amount before taxes and discounts are applied
   */
  subtotal: string;
  /**
   * tax_rate_overrides is the tax rate overrides to be applied to the invoice
   */
  taxRateOverrides?: Array<DtoTaxRateOverride> | undefined;
  /**
   * tax_rates
   */
  taxRates?: Array<string> | undefined;
  /**
   * total is the total amount of the invoice including taxes and discounts
   */
  total: string;
  /**
   * total_prepaid_applied is the total amount of prepaid applied to this invoice.
   */
  totalPrepaidApplied?: string | undefined;
};

/** @internal */
export type DtoCreateInvoiceRequest$Outbound = {
  amount_due: string;
  amount_paid?: string | undefined;
  billing_period?: string | undefined;
  billing_reason?: string | undefined;
  coupons?: Array<string> | undefined;
  currency: string;
  customer_id: string;
  description?: string | undefined;
  due_date?: string | undefined;
  idempotency_key?: string | undefined;
  invoice_coupons?: Array<DtoInvoiceCoupon$Outbound> | undefined;
  invoice_number?: string | undefined;
  invoice_pdf_url?: string | undefined;
  invoice_status?: string | undefined;
  invoice_type?: string | undefined;
  line_item_coupons?: Array<DtoInvoiceLineItemCoupon$Outbound> | undefined;
  line_items?: Array<DtoCreateInvoiceLineItemRequest$Outbound> | undefined;
  metadata?: { [k: string]: string } | undefined;
  payment_status?: string | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  prepared_tax_rates?: Array<DtoTaxRateResponse$Outbound> | undefined;
  subscription_id?: string | undefined;
  subtotal: string;
  tax_rate_overrides?: Array<DtoTaxRateOverride$Outbound> | undefined;
  tax_rates?: Array<string> | undefined;
  total: string;
  total_prepaid_applied?: string | undefined;
};

/** @internal */
export const DtoCreateInvoiceRequest$outboundSchema: z.ZodMiniType<
  DtoCreateInvoiceRequest$Outbound,
  DtoCreateInvoiceRequest
> = z.pipe(
  z.object({
    amountDue: z.string(),
    amountPaid: z.optional(z.string()),
    billingPeriod: z.optional(z.string()),
    billingReason: z.optional(InvoiceBillingReason$outboundSchema),
    coupons: z.optional(z.array(z.string())),
    currency: z.string(),
    customerId: z.string(),
    description: z.optional(z.string()),
    dueDate: z.optional(z.string()),
    idempotencyKey: z.optional(z.string()),
    invoiceCoupons: z.optional(z.array(DtoInvoiceCoupon$outboundSchema)),
    invoiceNumber: z.optional(z.string()),
    invoicePdfUrl: z.optional(z.string()),
    invoiceStatus: z.optional(InvoiceStatus$outboundSchema),
    invoiceType: z.optional(InvoiceType$outboundSchema),
    lineItemCoupons: z.optional(
      z.array(DtoInvoiceLineItemCoupon$outboundSchema),
    ),
    lineItems: z.optional(
      z.array(DtoCreateInvoiceLineItemRequest$outboundSchema),
    ),
    metadata: z.optional(z.record(z.string(), z.string())),
    paymentStatus: z.optional(PaymentStatus$outboundSchema),
    periodEnd: z.optional(z.string()),
    periodStart: z.optional(z.string()),
    preparedTaxRates: z.optional(z.array(DtoTaxRateResponse$outboundSchema)),
    subscriptionId: z.optional(z.string()),
    subtotal: z.string(),
    taxRateOverrides: z.optional(z.array(DtoTaxRateOverride$outboundSchema)),
    taxRates: z.optional(z.array(z.string())),
    total: z.string(),
    totalPrepaidApplied: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      amountDue: "amount_due",
      amountPaid: "amount_paid",
      billingPeriod: "billing_period",
      billingReason: "billing_reason",
      customerId: "customer_id",
      dueDate: "due_date",
      idempotencyKey: "idempotency_key",
      invoiceCoupons: "invoice_coupons",
      invoiceNumber: "invoice_number",
      invoicePdfUrl: "invoice_pdf_url",
      invoiceStatus: "invoice_status",
      invoiceType: "invoice_type",
      lineItemCoupons: "line_item_coupons",
      lineItems: "line_items",
      paymentStatus: "payment_status",
      periodEnd: "period_end",
      periodStart: "period_start",
      preparedTaxRates: "prepared_tax_rates",
      subscriptionId: "subscription_id",
      taxRateOverrides: "tax_rate_overrides",
      taxRates: "tax_rates",
      totalPrepaidApplied: "total_prepaid_applied",
    });
  }),
);

export function dtoCreateInvoiceRequestToJSON(
  dtoCreateInvoiceRequest: DtoCreateInvoiceRequest,
): string {
  return JSON.stringify(
    DtoCreateInvoiceRequest$outboundSchema.parse(dtoCreateInvoiceRequest),
  );
}
