/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  AlertSettings,
  AlertSettings$Outbound,
  AlertSettings$outboundSchema,
} from "./alert-settings.js";
import {
  DtoCreateMeterRequest,
  DtoCreateMeterRequest$Outbound,
  DtoCreateMeterRequest$outboundSchema,
} from "./dto-create-meter-request.js";
import { FeatureType, FeatureType$outboundSchema } from "./feature-type.js";

export type DtoCreateFeatureRequest = {
  alertSettings?: AlertSettings | undefined;
  description?: string | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: DtoCreateMeterRequest | undefined;
  meterId?: string | undefined;
  name: string;
  type: FeatureType;
  unitPlural?: string | undefined;
  unitSingular?: string | undefined;
};

/** @internal */
export type DtoCreateFeatureRequest$Outbound = {
  alert_settings?: AlertSettings$Outbound | undefined;
  description?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: DtoCreateMeterRequest$Outbound | undefined;
  meter_id?: string | undefined;
  name: string;
  type: string;
  unit_plural?: string | undefined;
  unit_singular?: string | undefined;
};

/** @internal */
export const DtoCreateFeatureRequest$outboundSchema: z.ZodMiniType<
  DtoCreateFeatureRequest$Outbound,
  DtoCreateFeatureRequest
> = z.pipe(
  z.object({
    alertSettings: z.optional(AlertSettings$outboundSchema),
    description: z.optional(z.string()),
    lookupKey: z.optional(z.string()),
    metadata: z.optional(z.record(z.string(), z.string())),
    meter: z.optional(DtoCreateMeterRequest$outboundSchema),
    meterId: z.optional(z.string()),
    name: z.string(),
    type: FeatureType$outboundSchema,
    unitPlural: z.optional(z.string()),
    unitSingular: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      alertSettings: "alert_settings",
      lookupKey: "lookup_key",
      meterId: "meter_id",
      unitPlural: "unit_plural",
      unitSingular: "unit_singular",
    });
  }),
);

export function dtoCreateFeatureRequestToJSON(
  dtoCreateFeatureRequest: DtoCreateFeatureRequest,
): string {
  return JSON.stringify(
    DtoCreateFeatureRequest$outboundSchema.parse(dtoCreateFeatureRequest),
  );
}
