/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoScheduledTaskResponse,
  DtoScheduledTaskResponse$inboundSchema,
} from "./dto-scheduled-task-response.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./pagination-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type DtoListScheduledTasksResponse = {
  items?: Array<DtoScheduledTaskResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListScheduledTasksResponse$inboundSchema: z.ZodMiniType<
  DtoListScheduledTasksResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoScheduledTaskResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function dtoListScheduledTasksResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListScheduledTasksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListScheduledTasksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListScheduledTasksResponse' from JSON`,
  );
}
