/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$inboundSchema,
} from "./dto-credit-grant-response.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./pagination-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type DtoListCreditGrantsResponse = {
  items?: Array<DtoCreditGrantResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListCreditGrantsResponse$inboundSchema: z.ZodMiniType<
  DtoListCreditGrantsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoCreditGrantResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function dtoListCreditGrantsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListCreditGrantsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListCreditGrantsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListCreditGrantsResponse' from JSON`,
  );
}
