/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import {
  ErrorsErrorDetail,
  ErrorsErrorDetail$inboundSchema,
} from "./errors-error-detail.js";
import { FlexPriceError } from "./flex-price-error.js";

export type ErrorsErrorsErrorResponseData = {
  error?: ErrorsErrorDetail | undefined;
  success?: boolean | undefined;
};

export class ErrorsErrorsErrorResponse extends FlexPriceError {
  error?: ErrorsErrorDetail | undefined;
  success?: boolean | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorsErrorsErrorResponseData;

  constructor(
    err: ErrorsErrorsErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.success != null) this.success = err.success;

    this.name = "ErrorsErrorsErrorResponse";
  }
}

/** @internal */
export const ErrorsErrorsErrorResponse$inboundSchema: z.ZodMiniType<
  ErrorsErrorsErrorResponse,
  unknown
> = z.pipe(
  z.object({
    error: types.optional(ErrorsErrorDetail$inboundSchema),
    success: types.optional(types.boolean()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ErrorsErrorsErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
