/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  ErrorsErrorDetail,
  ErrorsErrorDetail$inboundSchema,
} from "./errors-error-detail.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type ErrorsErrorResponse = {
  error?: ErrorsErrorDetail | undefined;
  success?: boolean | undefined;
};

/** @internal */
export const ErrorsErrorResponse$inboundSchema: z.ZodMiniType<
  ErrorsErrorResponse,
  unknown
> = z.object({
  error: types.optional(ErrorsErrorDetail$inboundSchema),
  success: types.optional(types.boolean()),
});

export function errorsErrorResponseFromJSON(
  jsonString: string,
): SafeParseResult<ErrorsErrorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorsErrorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorsErrorResponse' from JSON`,
  );
}
