/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoSubscriptionChangeRequest,
  DtoSubscriptionChangeRequest$Outbound,
  DtoSubscriptionChangeRequest$outboundSchema,
} from "./dto-subscription-change-request.js";

export type ExecuteSubscriptionChangeRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Subscription change request
   */
  body: DtoSubscriptionChangeRequest;
};

/** @internal */
export type ExecuteSubscriptionChangeRequest$Outbound = {
  id: string;
  body: DtoSubscriptionChangeRequest$Outbound;
};

/** @internal */
export const ExecuteSubscriptionChangeRequest$outboundSchema: z.ZodMiniType<
  ExecuteSubscriptionChangeRequest$Outbound,
  ExecuteSubscriptionChangeRequest
> = z.object({
  id: z.string(),
  body: DtoSubscriptionChangeRequest$outboundSchema,
});

export function executeSubscriptionChangeRequestToJSON(
  executeSubscriptionChangeRequest: ExecuteSubscriptionChangeRequest,
): string {
  return JSON.stringify(
    ExecuteSubscriptionChangeRequest$outboundSchema.parse(
      executeSubscriptionChangeRequest,
    ),
  );
}
