/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  ExecuteSubscriptionInheritanceRequest,
  ExecuteSubscriptionInheritanceRequest$Outbound,
  ExecuteSubscriptionInheritanceRequest$outboundSchema,
} from "./execute-subscription-inheritance-request.js";

export type ExecuteSubscriptionModifyRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * External customer IDs to inherit
   */
  body: ExecuteSubscriptionInheritanceRequest;
};

/** @internal */
export type ExecuteSubscriptionModifyRequest$Outbound = {
  id: string;
  body: ExecuteSubscriptionInheritanceRequest$Outbound;
};

/** @internal */
export const ExecuteSubscriptionModifyRequest$outboundSchema: z.ZodMiniType<
  ExecuteSubscriptionModifyRequest$Outbound,
  ExecuteSubscriptionModifyRequest
> = z.object({
  id: z.string(),
  body: ExecuteSubscriptionInheritanceRequest$outboundSchema,
});

export function executeSubscriptionModifyRequestToJSON(
  executeSubscriptionModifyRequest: ExecuteSubscriptionModifyRequest,
): string {
  return JSON.stringify(
    ExecuteSubscriptionModifyRequest$outboundSchema.parse(
      executeSubscriptionModifyRequest,
    ),
  );
}
