/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetInvoicePdfRequest = {
  /**
   * Invoice ID
   */
  id: string;
  /**
   * Return presigned URL from s3 instead of PDF
   */
  url?: boolean | undefined;
};

/** @internal */
export type GetInvoicePdfRequest$Outbound = {
  id: string;
  url?: boolean | undefined;
};

/** @internal */
export const GetInvoicePdfRequest$outboundSchema: z.ZodMiniType<
  GetInvoicePdfRequest$Outbound,
  GetInvoicePdfRequest
> = z.object({
  id: z.string(),
  url: z.optional(z.boolean()),
});

export function getInvoicePdfRequestToJSON(
  getInvoicePdfRequest: GetInvoicePdfRequest,
): string {
  return JSON.stringify(
    GetInvoicePdfRequest$outboundSchema.parse(getInvoicePdfRequest),
  );
}
