/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  AlertSettings,
  AlertSettings$inboundSchema,
} from "./alert-settings.js";
import { FeatureType, FeatureType$inboundSchema } from "./feature-type.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import { Status, Status$inboundSchema } from "./status.js";

export type GithubComFlexpriceFlexpriceInternalDomainFeatureFeature = {
  alertSettings?: AlertSettings | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  description?: string | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meterId?: string | undefined;
  name?: string | undefined;
  status?: Status | undefined;
  tenantId?: string | undefined;
  type?: FeatureType | undefined;
  unitPlural?: string | undefined;
  unitSingular?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const GithubComFlexpriceFlexpriceInternalDomainFeatureFeature$inboundSchema:
  z.ZodMiniType<
    GithubComFlexpriceFlexpriceInternalDomainFeatureFeature,
    unknown
  > = z.pipe(
    z.object({
      alert_settings: types.optional(AlertSettings$inboundSchema),
      created_at: types.optional(types.string()),
      created_by: types.optional(types.string()),
      description: types.optional(types.string()),
      environment_id: types.optional(types.string()),
      id: types.optional(types.string()),
      lookup_key: types.optional(types.string()),
      metadata: types.optional(z.record(z.string(), types.string())),
      meter_id: types.optional(types.string()),
      name: types.optional(types.string()),
      status: types.optional(Status$inboundSchema),
      tenant_id: types.optional(types.string()),
      type: types.optional(FeatureType$inboundSchema),
      unit_plural: types.optional(types.string()),
      unit_singular: types.optional(types.string()),
      updated_at: types.optional(types.string()),
      updated_by: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "alert_settings": "alertSettings",
        "created_at": "createdAt",
        "created_by": "createdBy",
        "environment_id": "environmentId",
        "lookup_key": "lookupKey",
        "meter_id": "meterId",
        "tenant_id": "tenantId",
        "unit_plural": "unitPlural",
        "unit_singular": "unitSingular",
        "updated_at": "updatedAt",
        "updated_by": "updatedBy",
      });
    }),
  );

export function githubComFlexpriceFlexpriceInternalDomainFeatureFeatureFromJSON(
  jsonString: string,
): SafeParseResult<
  GithubComFlexpriceFlexpriceInternalDomainFeatureFeature,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GithubComFlexpriceFlexpriceInternalDomainFeatureFeature$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GithubComFlexpriceFlexpriceInternalDomainFeatureFeature' from JSON`,
  );
}
