/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type HandleStripeWebhookRequest = {
  /**
   * Tenant ID
   */
  tenantId: string;
  /**
   * Environment ID
   */
  environmentId: string;
  /**
   * Stripe webhook signature
   */
  stripeSignature: string;
};

/** @internal */
export type HandleStripeWebhookRequest$Outbound = {
  tenant_id: string;
  environment_id: string;
  "Stripe-Signature": string;
};

/** @internal */
export const HandleStripeWebhookRequest$outboundSchema: z.ZodMiniType<
  HandleStripeWebhookRequest$Outbound,
  HandleStripeWebhookRequest
> = z.pipe(
  z.object({
    tenantId: z.string(),
    environmentId: z.string(),
    stripeSignature: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      tenantId: "tenant_id",
      environmentId: "environment_id",
      stripeSignature: "Stripe-Signature",
    });
  }),
);

export function handleStripeWebhookRequestToJSON(
  handleStripeWebhookRequest: HandleStripeWebhookRequest,
): string {
  return JSON.stringify(
    HandleStripeWebhookRequest$outboundSchema.parse(handleStripeWebhookRequest),
  );
}
