/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type HandleRazorpayWebhookRequest = {
  /**
   * Tenant ID
   */
  tenantId: string;
  /**
   * Environment ID
   */
  environmentId: string;
  /**
   * Razorpay webhook signature
   */
  xRazorpaySignature: string;
};

/** @internal */
export type HandleRazorpayWebhookRequest$Outbound = {
  tenant_id: string;
  environment_id: string;
  "X-Razorpay-Signature": string;
};

/** @internal */
export const HandleRazorpayWebhookRequest$outboundSchema: z.ZodMiniType<
  HandleRazorpayWebhookRequest$Outbound,
  HandleRazorpayWebhookRequest
> = z.pipe(
  z.object({
    tenantId: z.string(),
    environmentId: z.string(),
    xRazorpaySignature: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      tenantId: "tenant_id",
      environmentId: "environment_id",
      xRazorpaySignature: "X-Razorpay-Signature",
    });
  }),
);

export function handleRazorpayWebhookRequestToJSON(
  handleRazorpayWebhookRequest: HandleRazorpayWebhookRequest,
): string {
  return JSON.stringify(
    HandleRazorpayWebhookRequest$outboundSchema.parse(
      handleRazorpayWebhookRequest,
    ),
  );
}
