/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type HandlePaddleWebhookRequest = {
  /**
   * Tenant ID
   */
  tenantId: string;
  /**
   * Environment ID
   */
  environmentId: string;
  /**
   * Paddle webhook signature
   */
  paddleSignature: string;
};

/** @internal */
export type HandlePaddleWebhookRequest$Outbound = {
  tenant_id: string;
  environment_id: string;
  "Paddle-Signature": string;
};

/** @internal */
export const HandlePaddleWebhookRequest$outboundSchema: z.ZodMiniType<
  HandlePaddleWebhookRequest$Outbound,
  HandlePaddleWebhookRequest
> = z.pipe(
  z.object({
    tenantId: z.string(),
    environmentId: z.string(),
    paddleSignature: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      tenantId: "tenant_id",
      environmentId: "environment_id",
      paddleSignature: "Paddle-Signature",
    });
  }),
);

export function handlePaddleWebhookRequestToJSON(
  handlePaddleWebhookRequest: HandlePaddleWebhookRequest,
): string {
  return JSON.stringify(
    HandlePaddleWebhookRequest$outboundSchema.parse(handlePaddleWebhookRequest),
  );
}
