/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const InvoiceBillingReason = {
  SubscriptionCreate: "SUBSCRIPTION_CREATE",
  SubscriptionCycle: "SUBSCRIPTION_CYCLE",
  SubscriptionUpdate: "SUBSCRIPTION_UPDATE",
  SubscriptionTrialEnd: "SUBSCRIPTION_TRIAL_END",
  Proration: "PRORATION",
  Manual: "MANUAL",
} as const;
export type InvoiceBillingReason = ClosedEnum<typeof InvoiceBillingReason>;

/** @internal */
export const InvoiceBillingReason$outboundSchema: z.ZodMiniEnum<
  typeof InvoiceBillingReason
> = z.enum(InvoiceBillingReason);
