/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { Customer1, Customer1$inboundSchema } from "./customer-1.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./pagination-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";

/**
 * Response object for listing customers with pagination
 */
export type ListCustomersResponse = {
  items?: Array<Customer1> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const ListCustomersResponse$inboundSchema: z.ZodMiniType<
  ListCustomersResponse,
  unknown
> = z.object({
  items: types.optional(z.array(Customer1$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function listCustomersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCustomersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCustomersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCustomersResponse' from JSON`,
  );
}
