/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type MeterUsagePoint = {
  eventCount?: number | undefined;
  timestamp?: string | undefined;
  value?: string | undefined;
};

/** @internal */
export const MeterUsagePoint$inboundSchema: z.ZodMiniType<
  MeterUsagePoint,
  unknown
> = z.pipe(
  z.object({
    event_count: types.optional(types.number()),
    timestamp: types.optional(types.string()),
    value: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_count": "eventCount",
    });
  }),
);

export function meterUsagePointFromJSON(
  jsonString: string,
): SafeParseResult<MeterUsagePoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeterUsagePoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeterUsagePoint' from JSON`,
  );
}
