/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  AggregationType,
  AggregationType$inboundSchema,
} from "./aggregation-type.js";
import {
  MeterUsagePoint,
  MeterUsagePoint$inboundSchema,
} from "./meter-usage-point.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type MeterUsageQueryResponse = {
  aggregationType?: AggregationType | undefined;
  eventCount?: number | undefined;
  meterId?: string | undefined;
  points?: Array<MeterUsagePoint> | undefined;
  totalValue?: string | undefined;
};

/** @internal */
export const MeterUsageQueryResponse$inboundSchema: z.ZodMiniType<
  MeterUsageQueryResponse,
  unknown
> = z.pipe(
  z.object({
    aggregation_type: types.optional(AggregationType$inboundSchema),
    event_count: types.optional(types.number()),
    meter_id: types.optional(types.string()),
    points: types.optional(z.array(MeterUsagePoint$inboundSchema)),
    total_value: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "aggregation_type": "aggregationType",
      "event_count": "eventCount",
      "meter_id": "meterId",
      "total_value": "totalValue",
    });
  }),
);

export function meterUsageQueryResponseFromJSON(
  jsonString: string,
): SafeParseResult<MeterUsageQueryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeterUsageQueryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeterUsageQueryResponse' from JSON`,
  );
}
