/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  AggregationType,
  AggregationType$outboundSchema,
} from "./aggregation-type.js";
import { WindowSize, WindowSize$outboundSchema } from "./window-size.js";

export type MeterUsageAnalyticsRequest = {
  aggregationType: AggregationType;
  billingAnchor?: Date | undefined;
  endTime: Date;
  externalCustomerId: string;
  meterIds: Array<string>;
  startTime: Date;
  windowSize?: WindowSize | undefined;
};

/** @internal */
export type MeterUsageAnalyticsRequest$Outbound = {
  aggregation_type: string;
  billing_anchor?: string | undefined;
  end_time: string;
  external_customer_id: string;
  meter_ids: Array<string>;
  start_time: string;
  window_size?: string | undefined;
};

/** @internal */
export const MeterUsageAnalyticsRequest$outboundSchema: z.ZodMiniType<
  MeterUsageAnalyticsRequest$Outbound,
  MeterUsageAnalyticsRequest
> = z.pipe(
  z.object({
    aggregationType: AggregationType$outboundSchema,
    billingAnchor: z.optional(
      z.pipe(z.date(), z.transform(v => v.toISOString())),
    ),
    endTime: z.pipe(z.date(), z.transform(v => v.toISOString())),
    externalCustomerId: z.string(),
    meterIds: z.array(z.string()),
    startTime: z.pipe(z.date(), z.transform(v => v.toISOString())),
    windowSize: z.optional(WindowSize$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      aggregationType: "aggregation_type",
      billingAnchor: "billing_anchor",
      endTime: "end_time",
      externalCustomerId: "external_customer_id",
      meterIds: "meter_ids",
      startTime: "start_time",
      windowSize: "window_size",
    });
  }),
);

export function meterUsageAnalyticsRequestToJSON(
  meterUsageAnalyticsRequest: MeterUsageAnalyticsRequest,
): string {
  return JSON.stringify(
    MeterUsageAnalyticsRequest$outboundSchema.parse(meterUsageAnalyticsRequest),
  );
}
