/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoPauseSubscriptionRequest,
  DtoPauseSubscriptionRequest$Outbound,
  DtoPauseSubscriptionRequest$outboundSchema,
} from "./dto-pause-subscription-request.js";

export type PauseSubscriptionRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Pause subscription request
   */
  body: DtoPauseSubscriptionRequest;
};

/** @internal */
export type PauseSubscriptionRequest$Outbound = {
  id: string;
  body: DtoPauseSubscriptionRequest$Outbound;
};

/** @internal */
export const PauseSubscriptionRequest$outboundSchema: z.ZodMiniType<
  PauseSubscriptionRequest$Outbound,
  PauseSubscriptionRequest
> = z.object({
  id: z.string(),
  body: DtoPauseSubscriptionRequest$outboundSchema,
});

export function pauseSubscriptionRequestToJSON(
  pauseSubscriptionRequest: PauseSubscriptionRequest,
): string {
  return JSON.stringify(
    PauseSubscriptionRequest$outboundSchema.parse(pauseSubscriptionRequest),
  );
}
