/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoSubscriptionChangeRequest,
  DtoSubscriptionChangeRequest$Outbound,
  DtoSubscriptionChangeRequest$outboundSchema,
} from "./dto-subscription-change-request.js";

export type PreviewSubscriptionChangeRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Subscription change preview request
   */
  body: DtoSubscriptionChangeRequest;
};

/** @internal */
export type PreviewSubscriptionChangeRequest$Outbound = {
  id: string;
  body: DtoSubscriptionChangeRequest$Outbound;
};

/** @internal */
export const PreviewSubscriptionChangeRequest$outboundSchema: z.ZodMiniType<
  PreviewSubscriptionChangeRequest$Outbound,
  PreviewSubscriptionChangeRequest
> = z.object({
  id: z.string(),
  body: DtoSubscriptionChangeRequest$outboundSchema,
});

export function previewSubscriptionChangeRequestToJSON(
  previewSubscriptionChangeRequest: PreviewSubscriptionChangeRequest,
): string {
  return JSON.stringify(
    PreviewSubscriptionChangeRequest$outboundSchema.parse(
      previewSubscriptionChangeRequest,
    ),
  );
}
