/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RecalculateInvoiceRequest = {
  /**
   * Invoice ID
   */
  id: string;
  /**
   * Whether to finalize the invoice after recalculation (default: true)
   */
  finalize?: boolean | undefined;
};

/** @internal */
export type RecalculateInvoiceRequest$Outbound = {
  id: string;
  finalize?: boolean | undefined;
};

/** @internal */
export const RecalculateInvoiceRequest$outboundSchema: z.ZodMiniType<
  RecalculateInvoiceRequest$Outbound,
  RecalculateInvoiceRequest
> = z.object({
  id: z.string(),
  finalize: z.optional(z.boolean()),
});

export function recalculateInvoiceRequestToJSON(
  recalculateInvoiceRequest: RecalculateInvoiceRequest,
): string {
  return JSON.stringify(
    RecalculateInvoiceRequest$outboundSchema.parse(recalculateInvoiceRequest),
  );
}
