/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type RemoveAddonRequest = {
  addonAssociationId: string;
  reason?: string | undefined;
};

/** @internal */
export type RemoveAddonRequest$Outbound = {
  addon_association_id: string;
  reason?: string | undefined;
};

/** @internal */
export const RemoveAddonRequest$outboundSchema: z.ZodMiniType<
  RemoveAddonRequest$Outbound,
  RemoveAddonRequest
> = z.pipe(
  z.object({
    addonAssociationId: z.string(),
    reason: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      addonAssociationId: "addon_association_id",
    });
  }),
);

export function removeAddonRequestToJSON(
  removeAddonRequest: RemoveAddonRequest,
): string {
  return JSON.stringify(
    RemoveAddonRequest$outboundSchema.parse(removeAddonRequest),
  );
}
