/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  ResumeSubscriptionRequest,
  ResumeSubscriptionRequest$Outbound,
  ResumeSubscriptionRequest$outboundSchema,
} from "./resume-subscription-request.js";

export type ResumeSubscriptionRequestRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Resume subscription request
   */
  body: ResumeSubscriptionRequest;
};

/** @internal */
export type ResumeSubscriptionRequestRequest$Outbound = {
  id: string;
  body: ResumeSubscriptionRequest$Outbound;
};

/** @internal */
export const ResumeSubscriptionRequestRequest$outboundSchema: z.ZodMiniType<
  ResumeSubscriptionRequestRequest$Outbound,
  ResumeSubscriptionRequestRequest
> = z.object({
  id: z.string(),
  body: ResumeSubscriptionRequest$outboundSchema,
});

export function resumeSubscriptionRequestRequestToJSON(
  resumeSubscriptionRequestRequest: ResumeSubscriptionRequestRequest,
): string {
  return JSON.stringify(
    ResumeSubscriptionRequestRequest$outboundSchema.parse(
      resumeSubscriptionRequestRequest,
    ),
  );
}
