/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  BillingCadence,
  BillingCadence$outboundSchema,
} from "./billing-cadence.js";
import {
  BillingPeriod,
  BillingPeriod$outboundSchema,
} from "./billing-period.js";
import {
  FilterCondition,
  FilterCondition$Outbound,
  FilterCondition$outboundSchema,
} from "./filter-condition.js";
import {
  SortCondition,
  SortCondition$Outbound,
  SortCondition$outboundSchema,
} from "./sort-condition.js";
import { Status, Status$outboundSchema } from "./status.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$outboundSchema,
} from "./subscription-status.js";

export const SubscriptionFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type SubscriptionFilterOrder = ClosedEnum<
  typeof SubscriptionFilterOrder
>;

export type SubscriptionFilter = {
  /**
   * ActiveAt filters subscriptions that are active at the given time
   */
  activeAt?: string | undefined;
  /**
   * BillingCadence filters by billing cadence
   */
  billingCadence?: Array<BillingCadence> | undefined;
  /**
   * BillingPeriod filters by billing period
   */
  billingPeriod?: Array<BillingPeriod> | undefined;
  /**
   * CustomerID filters by customer ID
   */
  customerId?: string | undefined;
  endTime?: string | undefined;
  expand?: string | undefined;
  /**
   * ExternalCustomerID filters by external customer ID
   */
  externalCustomerId?: string | undefined;
  filters?: Array<FilterCondition> | undefined;
  /**
   * InvoicingCustomerIDs filters by invoicing customer ID
   */
  invoicingCustomerIds?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: SubscriptionFilterOrder | undefined;
  /**
   * ParentSubscriptionIDs filters by parent subscription IDs
   */
  parentSubscriptionIds?: Array<string> | undefined;
  /**
   * PlanID filters by plan ID
   */
  planId?: string | undefined;
  sort?: Array<SortCondition> | undefined;
  startTime?: string | undefined;
  status?: Status | undefined;
  subscriptionIds?: Array<string> | undefined;
  /**
   * SubscriptionStatus filters by subscription status
   */
  subscriptionStatus?: Array<SubscriptionStatus> | undefined;
  /**
   * WithLineItems includes line items in the response
   */
  withLineItems?: boolean | undefined;
};

/** @internal */
export const SubscriptionFilterOrder$outboundSchema: z.ZodMiniEnum<
  typeof SubscriptionFilterOrder
> = z.enum(SubscriptionFilterOrder);

/** @internal */
export type SubscriptionFilter$Outbound = {
  active_at?: string | undefined;
  billing_cadence?: Array<string> | undefined;
  billing_period?: Array<string> | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_customer_id?: string | undefined;
  filters?: Array<FilterCondition$Outbound> | undefined;
  invoicing_customer_ids?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  parent_subscription_ids?: Array<string> | undefined;
  plan_id?: string | undefined;
  sort?: Array<SortCondition$Outbound> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
  subscription_ids?: Array<string> | undefined;
  subscription_status?: Array<string> | undefined;
  with_line_items?: boolean | undefined;
};

/** @internal */
export const SubscriptionFilter$outboundSchema: z.ZodMiniType<
  SubscriptionFilter$Outbound,
  SubscriptionFilter
> = z.pipe(
  z.object({
    activeAt: z.optional(z.string()),
    billingCadence: z.optional(z.array(BillingCadence$outboundSchema)),
    billingPeriod: z.optional(z.array(BillingPeriod$outboundSchema)),
    customerId: z.optional(z.string()),
    endTime: z.optional(z.string()),
    expand: z.optional(z.string()),
    externalCustomerId: z.optional(z.string()),
    filters: z.optional(z.array(FilterCondition$outboundSchema)),
    invoicingCustomerIds: z.optional(z.array(z.string())),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    order: z.optional(SubscriptionFilterOrder$outboundSchema),
    parentSubscriptionIds: z.optional(z.array(z.string())),
    planId: z.optional(z.string()),
    sort: z.optional(z.array(SortCondition$outboundSchema)),
    startTime: z.optional(z.string()),
    status: z.optional(Status$outboundSchema),
    subscriptionIds: z.optional(z.array(z.string())),
    subscriptionStatus: z.optional(z.array(SubscriptionStatus$outboundSchema)),
    withLineItems: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      activeAt: "active_at",
      billingCadence: "billing_cadence",
      billingPeriod: "billing_period",
      customerId: "customer_id",
      endTime: "end_time",
      externalCustomerId: "external_customer_id",
      invoicingCustomerIds: "invoicing_customer_ids",
      parentSubscriptionIds: "parent_subscription_ids",
      planId: "plan_id",
      startTime: "start_time",
      subscriptionIds: "subscription_ids",
      subscriptionStatus: "subscription_status",
      withLineItems: "with_line_items",
    });
  }),
);

export function subscriptionFilterToJSON(
  subscriptionFilter: SubscriptionFilter,
): string {
  return JSON.stringify(
    SubscriptionFilter$outboundSchema.parse(subscriptionFilter),
  );
}
