/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type SubscriptionInheritanceConfig = {
  externalCustomerIdsToInheritSubscription?: Array<string> | undefined;
  invoicingCustomerExternalId?: string | undefined;
  parentSubscriptionId?: string | undefined;
};

/** @internal */
export type SubscriptionInheritanceConfig$Outbound = {
  external_customer_ids_to_inherit_subscription?: Array<string> | undefined;
  invoicing_customer_external_id?: string | undefined;
  parent_subscription_id?: string | undefined;
};

/** @internal */
export const SubscriptionInheritanceConfig$outboundSchema: z.ZodMiniType<
  SubscriptionInheritanceConfig$Outbound,
  SubscriptionInheritanceConfig
> = z.pipe(
  z.object({
    externalCustomerIdsToInheritSubscription: z.optional(z.array(z.string())),
    invoicingCustomerExternalId: z.optional(z.string()),
    parentSubscriptionId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      externalCustomerIdsToInheritSubscription:
        "external_customer_ids_to_inherit_subscription",
      invoicingCustomerExternalId: "invoicing_customer_external_id",
      parentSubscriptionId: "parent_subscription_id",
    });
  }),
);

export function subscriptionInheritanceConfigToJSON(
  subscriptionInheritanceConfig: SubscriptionInheritanceConfig,
): string {
  return JSON.stringify(
    SubscriptionInheritanceConfig$outboundSchema.parse(
      subscriptionInheritanceConfig,
    ),
  );
}
