/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoTriggerForceRunRequest,
  DtoTriggerForceRunRequest$Outbound,
  DtoTriggerForceRunRequest$outboundSchema,
} from "./dto-trigger-force-run-request.js";

export type TriggerScheduledTaskRunRequest = {
  /**
   * Scheduled Task ID
   */
  id: string;
  /**
   * Optional start and end time for custom range
   */
  body?: DtoTriggerForceRunRequest | undefined;
};

/** @internal */
export type TriggerScheduledTaskRunRequest$Outbound = {
  id: string;
  body?: DtoTriggerForceRunRequest$Outbound | undefined;
};

/** @internal */
export const TriggerScheduledTaskRunRequest$outboundSchema: z.ZodMiniType<
  TriggerScheduledTaskRunRequest$Outbound,
  TriggerScheduledTaskRunRequest
> = z.object({
  id: z.string(),
  body: z.optional(DtoTriggerForceRunRequest$outboundSchema),
});

export function triggerScheduledTaskRunRequestToJSON(
  triggerScheduledTaskRunRequest: TriggerScheduledTaskRunRequest,
): string {
  return JSON.stringify(
    TriggerScheduledTaskRunRequest$outboundSchema.parse(
      triggerScheduledTaskRunRequest,
    ),
  );
}
