/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  DtoUpdateCustomerRequest,
  DtoUpdateCustomerRequest$Outbound,
  DtoUpdateCustomerRequest$outboundSchema,
} from "./dto-update-customer-request.js";

export type UpdateCustomerRequest = {
  /**
   * Customer ID
   */
  id?: string | undefined;
  /**
   * Customer External ID
   */
  externalCustomerId?: string | undefined;
  /**
   * Customer
   */
  body: DtoUpdateCustomerRequest;
};

/** @internal */
export type UpdateCustomerRequest$Outbound = {
  id?: string | undefined;
  external_customer_id?: string | undefined;
  body: DtoUpdateCustomerRequest$Outbound;
};

/** @internal */
export const UpdateCustomerRequest$outboundSchema: z.ZodMiniType<
  UpdateCustomerRequest$Outbound,
  UpdateCustomerRequest
> = z.pipe(
  z.object({
    id: z.optional(z.string()),
    externalCustomerId: z.optional(z.string()),
    body: DtoUpdateCustomerRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      externalCustomerId: "external_customer_id",
    });
  }),
);

export function updateCustomerRequestToJSON(
  updateCustomerRequest: UpdateCustomerRequest,
): string {
  return JSON.stringify(
    UpdateCustomerRequest$outboundSchema.parse(updateCustomerRequest),
  );
}
