/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoUpdatePriceUnitRequest,
  DtoUpdatePriceUnitRequest$Outbound,
  DtoUpdatePriceUnitRequest$outboundSchema,
} from "./dto-update-price-unit-request.js";

export type UpdatePriceUnitRequest = {
  /**
   * Price unit ID
   */
  id: string;
  /**
   * Price unit details to update
   */
  body: DtoUpdatePriceUnitRequest;
};

/** @internal */
export type UpdatePriceUnitRequest$Outbound = {
  id: string;
  body: DtoUpdatePriceUnitRequest$Outbound;
};

/** @internal */
export const UpdatePriceUnitRequest$outboundSchema: z.ZodMiniType<
  UpdatePriceUnitRequest$Outbound,
  UpdatePriceUnitRequest
> = z.object({
  id: z.string(),
  body: DtoUpdatePriceUnitRequest$outboundSchema,
});

export function updatePriceUnitRequestToJSON(
  updatePriceUnitRequest: UpdatePriceUnitRequest,
): string {
  return JSON.stringify(
    UpdatePriceUnitRequest$outboundSchema.parse(updatePriceUnitRequest),
  );
}
