/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoUpdateInvoiceRequest,
  DtoUpdateInvoiceRequest$Outbound,
  DtoUpdateInvoiceRequest$outboundSchema,
} from "./dto-update-invoice-request.js";

export type UpdateInvoiceRequest = {
  /**
   * Invoice ID
   */
  id: string;
  /**
   * Invoice Update Request
   */
  body: DtoUpdateInvoiceRequest;
};

/** @internal */
export type UpdateInvoiceRequest$Outbound = {
  id: string;
  body: DtoUpdateInvoiceRequest$Outbound;
};

/** @internal */
export const UpdateInvoiceRequest$outboundSchema: z.ZodMiniType<
  UpdateInvoiceRequest$Outbound,
  UpdateInvoiceRequest
> = z.object({
  id: z.string(),
  body: DtoUpdateInvoiceRequest$outboundSchema,
});

export function updateInvoiceRequestToJSON(
  updateInvoiceRequest: UpdateInvoiceRequest,
): string {
  return JSON.stringify(
    UpdateInvoiceRequest$outboundSchema.parse(updateInvoiceRequest),
  );
}
