/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoUpdateCouponRequest,
  DtoUpdateCouponRequest$Outbound,
  DtoUpdateCouponRequest$outboundSchema,
} from "./dto-update-coupon-request.js";

export type UpdateCouponRequest = {
  /**
   * Coupon ID
   */
  id: string;
  /**
   * Coupon update request
   */
  body: DtoUpdateCouponRequest;
};

/** @internal */
export type UpdateCouponRequest$Outbound = {
  id: string;
  body: DtoUpdateCouponRequest$Outbound;
};

/** @internal */
export const UpdateCouponRequest$outboundSchema: z.ZodMiniType<
  UpdateCouponRequest$Outbound,
  UpdateCouponRequest
> = z.object({
  id: z.string(),
  body: DtoUpdateCouponRequest$outboundSchema,
});

export function updateCouponRequestToJSON(
  updateCouponRequest: UpdateCouponRequest,
): string {
  return JSON.stringify(
    UpdateCouponRequest$outboundSchema.parse(updateCouponRequest),
  );
}
