/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoUpdatePriceRequest,
  DtoUpdatePriceRequest$Outbound,
  DtoUpdatePriceRequest$outboundSchema,
} from "./dto-update-price-request.js";

export type UpdatePriceRequest = {
  /**
   * Price ID
   */
  id: string;
  /**
   * Price configuration
   */
  body: DtoUpdatePriceRequest;
};

/** @internal */
export type UpdatePriceRequest$Outbound = {
  id: string;
  body: DtoUpdatePriceRequest$Outbound;
};

/** @internal */
export const UpdatePriceRequest$outboundSchema: z.ZodMiniType<
  UpdatePriceRequest$Outbound,
  UpdatePriceRequest
> = z.object({
  id: z.string(),
  body: DtoUpdatePriceRequest$outboundSchema,
});

export function updatePriceRequestToJSON(
  updatePriceRequest: UpdatePriceRequest,
): string {
  return JSON.stringify(
    UpdatePriceRequest$outboundSchema.parse(updatePriceRequest),
  );
}
