/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoUpdateFeatureRequest,
  DtoUpdateFeatureRequest$Outbound,
  DtoUpdateFeatureRequest$outboundSchema,
} from "./dto-update-feature-request.js";

export type UpdateFeatureRequest = {
  /**
   * Feature ID
   */
  id: string;
  /**
   * Feature update data
   */
  body: DtoUpdateFeatureRequest;
};

/** @internal */
export type UpdateFeatureRequest$Outbound = {
  id: string;
  body: DtoUpdateFeatureRequest$Outbound;
};

/** @internal */
export const UpdateFeatureRequest$outboundSchema: z.ZodMiniType<
  UpdateFeatureRequest$Outbound,
  UpdateFeatureRequest
> = z.object({
  id: z.string(),
  body: DtoUpdateFeatureRequest$outboundSchema,
});

export function updateFeatureRequestToJSON(
  updateFeatureRequest: UpdateFeatureRequest,
): string {
  return JSON.stringify(
    UpdateFeatureRequest$outboundSchema.parse(updateFeatureRequest),
  );
}
