/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoUpdateSubscriptionLineItemRequest,
  DtoUpdateSubscriptionLineItemRequest$Outbound,
  DtoUpdateSubscriptionLineItemRequest$outboundSchema,
} from "./dto-update-subscription-line-item-request.js";

export type UpdateSubscriptionLineItemRequest = {
  /**
   * Line Item ID
   */
  id: string;
  /**
   * Update Line Item Request
   */
  body: DtoUpdateSubscriptionLineItemRequest;
};

/** @internal */
export type UpdateSubscriptionLineItemRequest$Outbound = {
  id: string;
  body: DtoUpdateSubscriptionLineItemRequest$Outbound;
};

/** @internal */
export const UpdateSubscriptionLineItemRequest$outboundSchema: z.ZodMiniType<
  UpdateSubscriptionLineItemRequest$Outbound,
  UpdateSubscriptionLineItemRequest
> = z.object({
  id: z.string(),
  body: DtoUpdateSubscriptionLineItemRequest$outboundSchema,
});

export function updateSubscriptionLineItemRequestToJSON(
  updateSubscriptionLineItemRequest: UpdateSubscriptionLineItemRequest,
): string {
  return JSON.stringify(
    UpdateSubscriptionLineItemRequest$outboundSchema.parse(
      updateSubscriptionLineItemRequest,
    ),
  );
}
