/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DtoUpdateEnvironmentRequest,
  DtoUpdateEnvironmentRequest$Outbound,
  DtoUpdateEnvironmentRequest$outboundSchema,
} from "./dto-update-environment-request.js";

export type UpdateEnvironmentRequest = {
  /**
   * Environment ID
   */
  id: string;
  /**
   * Environment
   */
  body: DtoUpdateEnvironmentRequest;
};

/** @internal */
export type UpdateEnvironmentRequest$Outbound = {
  id: string;
  body: DtoUpdateEnvironmentRequest$Outbound;
};

/** @internal */
export const UpdateEnvironmentRequest$outboundSchema: z.ZodMiniType<
  UpdateEnvironmentRequest$Outbound,
  UpdateEnvironmentRequest
> = z.object({
  id: z.string(),
  body: DtoUpdateEnvironmentRequest$outboundSchema,
});

export function updateEnvironmentRequestToJSON(
  updateEnvironmentRequest: UpdateEnvironmentRequest,
): string {
  return JSON.stringify(
    UpdateEnvironmentRequest$outboundSchema.parse(updateEnvironmentRequest),
  );
}
