/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$inboundSchema,
} from "./dto-customer-response.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$inboundSchema,
} from "./dto-wallet-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  WebhookDtoWalletAlertInfo,
  WebhookDtoWalletAlertInfo$inboundSchema,
} from "./webhook-dto-wallet-alert-info.js";

export type WebhookDtoWalletWebhookPayload = {
  alert?: WebhookDtoWalletAlertInfo | undefined;
  /**
   * Customer response object containing all customer information
   */
  customer?: DtoCustomerResponse | undefined;
  eventType?: string | undefined;
  wallet?: DtoWalletResponse | undefined;
};

/** @internal */
export const WebhookDtoWalletWebhookPayload$inboundSchema: z.ZodMiniType<
  WebhookDtoWalletWebhookPayload,
  unknown
> = z.pipe(
  z.object({
    alert: types.optional(WebhookDtoWalletAlertInfo$inboundSchema),
    customer: types.optional(DtoCustomerResponse$inboundSchema),
    event_type: types.optional(types.string()),
    wallet: types.optional(DtoWalletResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_type": "eventType",
    });
  }),
);

export function webhookDtoWalletWebhookPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoWalletWebhookPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDtoWalletWebhookPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoWalletWebhookPayload' from JSON`,
  );
}
