/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$inboundSchema,
} from "./dto-wallet-response.js";
import {
  DtoWalletTransactionResponse,
  DtoWalletTransactionResponse$inboundSchema,
} from "./dto-wallet-transaction-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  WebhookEventName,
  WebhookEventName$inboundSchema,
} from "./webhook-event-name.js";

export type WebhookDtoTransactionWebhookPayload = {
  eventType?: WebhookEventName | undefined;
  transaction?: DtoWalletTransactionResponse | undefined;
  wallet?: DtoWalletResponse | undefined;
};

/** @internal */
export const WebhookDtoTransactionWebhookPayload$inboundSchema: z.ZodMiniType<
  WebhookDtoTransactionWebhookPayload,
  unknown
> = z.pipe(
  z.object({
    event_type: types.optional(WebhookEventName$inboundSchema),
    transaction: types.optional(DtoWalletTransactionResponse$inboundSchema),
    wallet: types.optional(DtoWalletResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_type": "eventType",
    });
  }),
);

export function webhookDtoTransactionWebhookPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoTransactionWebhookPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookDtoTransactionWebhookPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoTransactionWebhookPayload' from JSON`,
  );
}
