/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { Customer1, Customer1$inboundSchema } from "./customer-1.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import { Wallet, Wallet$inboundSchema } from "./wallet.js";
import {
  WebhookDtoWalletAlertInfo,
  WebhookDtoWalletAlertInfo$inboundSchema,
} from "./webhook-dto-wallet-alert-info.js";
import {
  WebhookEventName,
  WebhookEventName$inboundSchema,
} from "./webhook-event-name.js";

export type WebhookDtoWalletWebhookPayload = {
  alert?: WebhookDtoWalletAlertInfo | undefined;
  /**
   * Customer response object containing all customer information
   */
  customer?: Customer1 | undefined;
  eventType?: WebhookEventName | undefined;
  wallet?: Wallet | undefined;
};

/** @internal */
export const WebhookDtoWalletWebhookPayload$inboundSchema: z.ZodMiniType<
  WebhookDtoWalletWebhookPayload,
  unknown
> = z.pipe(
  z.object({
    alert: types.optional(WebhookDtoWalletAlertInfo$inboundSchema),
    customer: types.optional(Customer1$inboundSchema),
    event_type: types.optional(WebhookEventName$inboundSchema),
    wallet: types.optional(Wallet$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_type": "eventType",
    });
  }),
);

export function webhookDtoWalletWebhookPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoWalletWebhookPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDtoWalletWebhookPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoWalletWebhookPayload' from JSON`,
  );
}
