/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DtoIngestEventRequest from './DtoIngestEventRequest';

/**
 * The DtoBulkIngestEventRequest model module.
 * @module model/DtoBulkIngestEventRequest
 * @version 1.0
 */
class DtoBulkIngestEventRequest {
    /**
     * Constructs a new <code>DtoBulkIngestEventRequest</code>.
     * @alias module:model/DtoBulkIngestEventRequest
     * @param events {Array.<module:model/DtoIngestEventRequest>} 
     */
    constructor(events) { 
        
        DtoBulkIngestEventRequest.initialize(this, events);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, events) { 
        obj['events'] = events;
    }

    /**
     * Constructs a <code>DtoBulkIngestEventRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DtoBulkIngestEventRequest} obj Optional instance to populate.
     * @return {module:model/DtoBulkIngestEventRequest} The populated <code>DtoBulkIngestEventRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DtoBulkIngestEventRequest();

            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [DtoIngestEventRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DtoBulkIngestEventRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DtoBulkIngestEventRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DtoBulkIngestEventRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['events']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['events'])) {
                throw new Error("Expected the field `events` to be an array in the JSON data but got " + data['events']);
            }
            // validate the optional field `events` (array)
            for (const item of data['events']) {
                DtoIngestEventRequest.validateJSON(item);
            };
        }

        return true;
    }


}

DtoBulkIngestEventRequest.RequiredProperties = ["events"];

/**
 * @member {Array.<module:model/DtoIngestEventRequest>} events
 */
DtoBulkIngestEventRequest.prototype['events'] = undefined;






export default DtoBulkIngestEventRequest;

