/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DtoCreateInvoiceLineItemRequest from './DtoCreateInvoiceLineItemRequest';
import TypesInvoiceBillingReason from './TypesInvoiceBillingReason';
import TypesInvoiceStatus from './TypesInvoiceStatus';
import TypesInvoiceType from './TypesInvoiceType';
import TypesPaymentStatus from './TypesPaymentStatus';

/**
 * The DtoCreateInvoiceRequest model module.
 * @module model/DtoCreateInvoiceRequest
 * @version 1.0
 */
class DtoCreateInvoiceRequest {
    /**
     * Constructs a new <code>DtoCreateInvoiceRequest</code>.
     * @alias module:model/DtoCreateInvoiceRequest
     * @param amountDue {Number} 
     * @param currency {String} 
     * @param customerId {String} 
     */
    constructor(amountDue, currency, customerId) { 
        
        DtoCreateInvoiceRequest.initialize(this, amountDue, currency, customerId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amountDue, currency, customerId) { 
        obj['amount_due'] = amountDue;
        obj['currency'] = currency;
        obj['customer_id'] = customerId;
    }

    /**
     * Constructs a <code>DtoCreateInvoiceRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DtoCreateInvoiceRequest} obj Optional instance to populate.
     * @return {module:model/DtoCreateInvoiceRequest} The populated <code>DtoCreateInvoiceRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DtoCreateInvoiceRequest();

            if (data.hasOwnProperty('amount_due')) {
                obj['amount_due'] = ApiClient.convertToType(data['amount_due'], 'Number');
            }
            if (data.hasOwnProperty('amount_paid')) {
                obj['amount_paid'] = ApiClient.convertToType(data['amount_paid'], 'Number');
            }
            if (data.hasOwnProperty('billing_period')) {
                obj['billing_period'] = ApiClient.convertToType(data['billing_period'], 'String');
            }
            if (data.hasOwnProperty('billing_reason')) {
                obj['billing_reason'] = TypesInvoiceBillingReason.constructFromObject(data['billing_reason']);
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('customer_id')) {
                obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('due_date')) {
                obj['due_date'] = ApiClient.convertToType(data['due_date'], 'String');
            }
            if (data.hasOwnProperty('environment_id')) {
                obj['environment_id'] = ApiClient.convertToType(data['environment_id'], 'String');
            }
            if (data.hasOwnProperty('idempotency_key')) {
                obj['idempotency_key'] = ApiClient.convertToType(data['idempotency_key'], 'String');
            }
            if (data.hasOwnProperty('invoice_status')) {
                obj['invoice_status'] = TypesInvoiceStatus.constructFromObject(data['invoice_status']);
            }
            if (data.hasOwnProperty('invoice_type')) {
                obj['invoice_type'] = TypesInvoiceType.constructFromObject(data['invoice_type']);
            }
            if (data.hasOwnProperty('line_items')) {
                obj['line_items'] = ApiClient.convertToType(data['line_items'], [DtoCreateInvoiceLineItemRequest]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': 'String'});
            }
            if (data.hasOwnProperty('payment_status')) {
                obj['payment_status'] = TypesPaymentStatus.constructFromObject(data['payment_status']);
            }
            if (data.hasOwnProperty('period_end')) {
                obj['period_end'] = ApiClient.convertToType(data['period_end'], 'String');
            }
            if (data.hasOwnProperty('period_start')) {
                obj['period_start'] = ApiClient.convertToType(data['period_start'], 'String');
            }
            if (data.hasOwnProperty('subscription_id')) {
                obj['subscription_id'] = ApiClient.convertToType(data['subscription_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DtoCreateInvoiceRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DtoCreateInvoiceRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DtoCreateInvoiceRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['billing_period'] && !(typeof data['billing_period'] === 'string' || data['billing_period'] instanceof String)) {
            throw new Error("Expected the field `billing_period` to be a primitive type in the JSON string but got " + data['billing_period']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['customer_id'] && !(typeof data['customer_id'] === 'string' || data['customer_id'] instanceof String)) {
            throw new Error("Expected the field `customer_id` to be a primitive type in the JSON string but got " + data['customer_id']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['due_date'] && !(typeof data['due_date'] === 'string' || data['due_date'] instanceof String)) {
            throw new Error("Expected the field `due_date` to be a primitive type in the JSON string but got " + data['due_date']);
        }
        // ensure the json data is a string
        if (data['environment_id'] && !(typeof data['environment_id'] === 'string' || data['environment_id'] instanceof String)) {
            throw new Error("Expected the field `environment_id` to be a primitive type in the JSON string but got " + data['environment_id']);
        }
        // ensure the json data is a string
        if (data['idempotency_key'] && !(typeof data['idempotency_key'] === 'string' || data['idempotency_key'] instanceof String)) {
            throw new Error("Expected the field `idempotency_key` to be a primitive type in the JSON string but got " + data['idempotency_key']);
        }
        if (data['line_items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['line_items'])) {
                throw new Error("Expected the field `line_items` to be an array in the JSON data but got " + data['line_items']);
            }
            // validate the optional field `line_items` (array)
            for (const item of data['line_items']) {
                DtoCreateInvoiceLineItemRequest.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['period_end'] && !(typeof data['period_end'] === 'string' || data['period_end'] instanceof String)) {
            throw new Error("Expected the field `period_end` to be a primitive type in the JSON string but got " + data['period_end']);
        }
        // ensure the json data is a string
        if (data['period_start'] && !(typeof data['period_start'] === 'string' || data['period_start'] instanceof String)) {
            throw new Error("Expected the field `period_start` to be a primitive type in the JSON string but got " + data['period_start']);
        }
        // ensure the json data is a string
        if (data['subscription_id'] && !(typeof data['subscription_id'] === 'string' || data['subscription_id'] instanceof String)) {
            throw new Error("Expected the field `subscription_id` to be a primitive type in the JSON string but got " + data['subscription_id']);
        }

        return true;
    }


}

DtoCreateInvoiceRequest.RequiredProperties = ["amount_due", "currency", "customer_id"];

/**
 * @member {Number} amount_due
 */
DtoCreateInvoiceRequest.prototype['amount_due'] = undefined;

/**
 * @member {Number} amount_paid
 */
DtoCreateInvoiceRequest.prototype['amount_paid'] = undefined;

/**
 * @member {String} billing_period
 */
DtoCreateInvoiceRequest.prototype['billing_period'] = undefined;

/**
 * @member {module:model/TypesInvoiceBillingReason} billing_reason
 */
DtoCreateInvoiceRequest.prototype['billing_reason'] = undefined;

/**
 * @member {String} currency
 */
DtoCreateInvoiceRequest.prototype['currency'] = undefined;

/**
 * @member {String} customer_id
 */
DtoCreateInvoiceRequest.prototype['customer_id'] = undefined;

/**
 * @member {String} description
 */
DtoCreateInvoiceRequest.prototype['description'] = undefined;

/**
 * @member {String} due_date
 */
DtoCreateInvoiceRequest.prototype['due_date'] = undefined;

/**
 * @member {String} environment_id
 */
DtoCreateInvoiceRequest.prototype['environment_id'] = undefined;

/**
 * @member {String} idempotency_key
 */
DtoCreateInvoiceRequest.prototype['idempotency_key'] = undefined;

/**
 * @member {module:model/TypesInvoiceStatus} invoice_status
 */
DtoCreateInvoiceRequest.prototype['invoice_status'] = undefined;

/**
 * @member {module:model/TypesInvoiceType} invoice_type
 */
DtoCreateInvoiceRequest.prototype['invoice_type'] = undefined;

/**
 * @member {Array.<module:model/DtoCreateInvoiceLineItemRequest>} line_items
 */
DtoCreateInvoiceRequest.prototype['line_items'] = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
DtoCreateInvoiceRequest.prototype['metadata'] = undefined;

/**
 * @member {module:model/TypesPaymentStatus} payment_status
 */
DtoCreateInvoiceRequest.prototype['payment_status'] = undefined;

/**
 * @member {String} period_end
 */
DtoCreateInvoiceRequest.prototype['period_end'] = undefined;

/**
 * @member {String} period_start
 */
DtoCreateInvoiceRequest.prototype['period_start'] = undefined;

/**
 * @member {String} subscription_id
 */
DtoCreateInvoiceRequest.prototype['subscription_id'] = undefined;






export default DtoCreateInvoiceRequest;

