/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DtoCreatePlanEntitlementRequest from './DtoCreatePlanEntitlementRequest';
import DtoCreatePlanPriceRequest from './DtoCreatePlanPriceRequest';

/**
 * The DtoCreatePlanRequest model module.
 * @module model/DtoCreatePlanRequest
 * @version 1.0
 */
class DtoCreatePlanRequest {
    /**
     * Constructs a new <code>DtoCreatePlanRequest</code>.
     * @alias module:model/DtoCreatePlanRequest
     * @param name {String} 
     */
    constructor(name) { 
        
        DtoCreatePlanRequest.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>DtoCreatePlanRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DtoCreatePlanRequest} obj Optional instance to populate.
     * @return {module:model/DtoCreatePlanRequest} The populated <code>DtoCreatePlanRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DtoCreatePlanRequest();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('entitlements')) {
                obj['entitlements'] = ApiClient.convertToType(data['entitlements'], [DtoCreatePlanEntitlementRequest]);
            }
            if (data.hasOwnProperty('lookup_key')) {
                obj['lookup_key'] = ApiClient.convertToType(data['lookup_key'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('prices')) {
                obj['prices'] = ApiClient.convertToType(data['prices'], [DtoCreatePlanPriceRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DtoCreatePlanRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DtoCreatePlanRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DtoCreatePlanRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['entitlements']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['entitlements'])) {
                throw new Error("Expected the field `entitlements` to be an array in the JSON data but got " + data['entitlements']);
            }
            // validate the optional field `entitlements` (array)
            for (const item of data['entitlements']) {
                DtoCreatePlanEntitlementRequest.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['lookup_key'] && !(typeof data['lookup_key'] === 'string' || data['lookup_key'] instanceof String)) {
            throw new Error("Expected the field `lookup_key` to be a primitive type in the JSON string but got " + data['lookup_key']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['prices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['prices'])) {
                throw new Error("Expected the field `prices` to be an array in the JSON data but got " + data['prices']);
            }
            // validate the optional field `prices` (array)
            for (const item of data['prices']) {
                DtoCreatePlanPriceRequest.validateJSON(item);
            };
        }

        return true;
    }


}

DtoCreatePlanRequest.RequiredProperties = ["name"];

/**
 * @member {String} description
 */
DtoCreatePlanRequest.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/DtoCreatePlanEntitlementRequest>} entitlements
 */
DtoCreatePlanRequest.prototype['entitlements'] = undefined;

/**
 * @member {String} lookup_key
 */
DtoCreatePlanRequest.prototype['lookup_key'] = undefined;

/**
 * @member {String} name
 */
DtoCreatePlanRequest.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/DtoCreatePlanPriceRequest>} prices
 */
DtoCreatePlanRequest.prototype['prices'] = undefined;






export default DtoCreatePlanRequest;

