/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DtoAggregatedFeature from './DtoAggregatedFeature';

/**
 * The DtoCustomerEntitlementsResponse model module.
 * @module model/DtoCustomerEntitlementsResponse
 * @version 1.0
 */
class DtoCustomerEntitlementsResponse {
    /**
     * Constructs a new <code>DtoCustomerEntitlementsResponse</code>.
     * @alias module:model/DtoCustomerEntitlementsResponse
     */
    constructor() { 
        
        DtoCustomerEntitlementsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DtoCustomerEntitlementsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DtoCustomerEntitlementsResponse} obj Optional instance to populate.
     * @return {module:model/DtoCustomerEntitlementsResponse} The populated <code>DtoCustomerEntitlementsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DtoCustomerEntitlementsResponse();

            if (data.hasOwnProperty('customer_id')) {
                obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'String');
            }
            if (data.hasOwnProperty('features')) {
                obj['features'] = ApiClient.convertToType(data['features'], [DtoAggregatedFeature]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DtoCustomerEntitlementsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DtoCustomerEntitlementsResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['customer_id'] && !(typeof data['customer_id'] === 'string' || data['customer_id'] instanceof String)) {
            throw new Error("Expected the field `customer_id` to be a primitive type in the JSON string but got " + data['customer_id']);
        }
        if (data['features']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['features'])) {
                throw new Error("Expected the field `features` to be an array in the JSON data but got " + data['features']);
            }
            // validate the optional field `features` (array)
            for (const item of data['features']) {
                DtoAggregatedFeature.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} customer_id
 */
DtoCustomerEntitlementsResponse.prototype['customer_id'] = undefined;

/**
 * @member {Array.<module:model/DtoAggregatedFeature>} features
 */
DtoCustomerEntitlementsResponse.prototype['features'] = undefined;






export default DtoCustomerEntitlementsResponse;

