/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DtoGetPreviewInvoiceRequest model module.
 * @module model/DtoGetPreviewInvoiceRequest
 * @version 1.0
 */
class DtoGetPreviewInvoiceRequest {
    /**
     * Constructs a new <code>DtoGetPreviewInvoiceRequest</code>.
     * @alias module:model/DtoGetPreviewInvoiceRequest
     * @param subscriptionId {String} 
     */
    constructor(subscriptionId) { 
        
        DtoGetPreviewInvoiceRequest.initialize(this, subscriptionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, subscriptionId) { 
        obj['subscription_id'] = subscriptionId;
    }

    /**
     * Constructs a <code>DtoGetPreviewInvoiceRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DtoGetPreviewInvoiceRequest} obj Optional instance to populate.
     * @return {module:model/DtoGetPreviewInvoiceRequest} The populated <code>DtoGetPreviewInvoiceRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DtoGetPreviewInvoiceRequest();

            if (data.hasOwnProperty('period_end')) {
                obj['period_end'] = ApiClient.convertToType(data['period_end'], 'String');
            }
            if (data.hasOwnProperty('period_start')) {
                obj['period_start'] = ApiClient.convertToType(data['period_start'], 'String');
            }
            if (data.hasOwnProperty('subscription_id')) {
                obj['subscription_id'] = ApiClient.convertToType(data['subscription_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DtoGetPreviewInvoiceRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DtoGetPreviewInvoiceRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DtoGetPreviewInvoiceRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['period_end'] && !(typeof data['period_end'] === 'string' || data['period_end'] instanceof String)) {
            throw new Error("Expected the field `period_end` to be a primitive type in the JSON string but got " + data['period_end']);
        }
        // ensure the json data is a string
        if (data['period_start'] && !(typeof data['period_start'] === 'string' || data['period_start'] instanceof String)) {
            throw new Error("Expected the field `period_start` to be a primitive type in the JSON string but got " + data['period_start']);
        }
        // ensure the json data is a string
        if (data['subscription_id'] && !(typeof data['subscription_id'] === 'string' || data['subscription_id'] instanceof String)) {
            throw new Error("Expected the field `subscription_id` to be a primitive type in the JSON string but got " + data['subscription_id']);
        }

        return true;
    }


}

DtoGetPreviewInvoiceRequest.RequiredProperties = ["subscription_id"];

/**
 * @member {String} period_end
 */
DtoGetPreviewInvoiceRequest.prototype['period_end'] = undefined;

/**
 * @member {String} period_start
 */
DtoGetPreviewInvoiceRequest.prototype['period_start'] = undefined;

/**
 * @member {String} subscription_id
 */
DtoGetPreviewInvoiceRequest.prototype['subscription_id'] = undefined;






export default DtoGetPreviewInvoiceRequest;

