/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DtoSubscriptionPauseResponse from './DtoSubscriptionPauseResponse';

/**
 * The DtoListSubscriptionPausesResponse model module.
 * @module model/DtoListSubscriptionPausesResponse
 * @version 1.0
 */
class DtoListSubscriptionPausesResponse {
    /**
     * Constructs a new <code>DtoListSubscriptionPausesResponse</code>.
     * @alias module:model/DtoListSubscriptionPausesResponse
     */
    constructor() { 
        
        DtoListSubscriptionPausesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DtoListSubscriptionPausesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DtoListSubscriptionPausesResponse} obj Optional instance to populate.
     * @return {module:model/DtoListSubscriptionPausesResponse} The populated <code>DtoListSubscriptionPausesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DtoListSubscriptionPausesResponse();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [DtoSubscriptionPauseResponse]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DtoListSubscriptionPausesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DtoListSubscriptionPausesResponse</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                DtoSubscriptionPauseResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/DtoSubscriptionPauseResponse>} items
 */
DtoListSubscriptionPausesResponse.prototype['items'] = undefined;

/**
 * @member {Number} total
 */
DtoListSubscriptionPausesResponse.prototype['total'] = undefined;






export default DtoListSubscriptionPausesResponse;

