/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TypesEntityType from './TypesEntityType';
import TypesFileType from './TypesFileType';
import TypesTaskStatus from './TypesTaskStatus';
import TypesTaskType from './TypesTaskType';

/**
 * The DtoTaskResponse model module.
 * @module model/DtoTaskResponse
 * @version 1.0
 */
class DtoTaskResponse {
    /**
     * Constructs a new <code>DtoTaskResponse</code>.
     * @alias module:model/DtoTaskResponse
     */
    constructor() { 
        
        DtoTaskResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DtoTaskResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DtoTaskResponse} obj Optional instance to populate.
     * @return {module:model/DtoTaskResponse} The populated <code>DtoTaskResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DtoTaskResponse();

            if (data.hasOwnProperty('completed_at')) {
                obj['completed_at'] = ApiClient.convertToType(data['completed_at'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String');
            }
            if (data.hasOwnProperty('entity_type')) {
                obj['entity_type'] = TypesEntityType.constructFromObject(data['entity_type']);
            }
            if (data.hasOwnProperty('error_summary')) {
                obj['error_summary'] = ApiClient.convertToType(data['error_summary'], 'String');
            }
            if (data.hasOwnProperty('failed_at')) {
                obj['failed_at'] = ApiClient.convertToType(data['failed_at'], 'String');
            }
            if (data.hasOwnProperty('failed_records')) {
                obj['failed_records'] = ApiClient.convertToType(data['failed_records'], 'Number');
            }
            if (data.hasOwnProperty('file_name')) {
                obj['file_name'] = ApiClient.convertToType(data['file_name'], 'String');
            }
            if (data.hasOwnProperty('file_type')) {
                obj['file_type'] = TypesFileType.constructFromObject(data['file_type']);
            }
            if (data.hasOwnProperty('file_url')) {
                obj['file_url'] = ApiClient.convertToType(data['file_url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': Object});
            }
            if (data.hasOwnProperty('processed_records')) {
                obj['processed_records'] = ApiClient.convertToType(data['processed_records'], 'Number');
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('successful_records')) {
                obj['successful_records'] = ApiClient.convertToType(data['successful_records'], 'Number');
            }
            if (data.hasOwnProperty('task_status')) {
                obj['task_status'] = TypesTaskStatus.constructFromObject(data['task_status']);
            }
            if (data.hasOwnProperty('task_type')) {
                obj['task_type'] = TypesTaskType.constructFromObject(data['task_type']);
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
            if (data.hasOwnProperty('total_records')) {
                obj['total_records'] = ApiClient.convertToType(data['total_records'], 'Number');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('updated_by')) {
                obj['updated_by'] = ApiClient.convertToType(data['updated_by'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DtoTaskResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DtoTaskResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['completed_at'] && !(typeof data['completed_at'] === 'string' || data['completed_at'] instanceof String)) {
            throw new Error("Expected the field `completed_at` to be a primitive type in the JSON string but got " + data['completed_at']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['created_by'] && !(typeof data['created_by'] === 'string' || data['created_by'] instanceof String)) {
            throw new Error("Expected the field `created_by` to be a primitive type in the JSON string but got " + data['created_by']);
        }
        // ensure the json data is a string
        if (data['error_summary'] && !(typeof data['error_summary'] === 'string' || data['error_summary'] instanceof String)) {
            throw new Error("Expected the field `error_summary` to be a primitive type in the JSON string but got " + data['error_summary']);
        }
        // ensure the json data is a string
        if (data['failed_at'] && !(typeof data['failed_at'] === 'string' || data['failed_at'] instanceof String)) {
            throw new Error("Expected the field `failed_at` to be a primitive type in the JSON string but got " + data['failed_at']);
        }
        // ensure the json data is a string
        if (data['file_name'] && !(typeof data['file_name'] === 'string' || data['file_name'] instanceof String)) {
            throw new Error("Expected the field `file_name` to be a primitive type in the JSON string but got " + data['file_name']);
        }
        // ensure the json data is a string
        if (data['file_url'] && !(typeof data['file_url'] === 'string' || data['file_url'] instanceof String)) {
            throw new Error("Expected the field `file_url` to be a primitive type in the JSON string but got " + data['file_url']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['started_at'] && !(typeof data['started_at'] === 'string' || data['started_at'] instanceof String)) {
            throw new Error("Expected the field `started_at` to be a primitive type in the JSON string but got " + data['started_at']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['tenant_id'] && !(typeof data['tenant_id'] === 'string' || data['tenant_id'] instanceof String)) {
            throw new Error("Expected the field `tenant_id` to be a primitive type in the JSON string but got " + data['tenant_id']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }
        // ensure the json data is a string
        if (data['updated_by'] && !(typeof data['updated_by'] === 'string' || data['updated_by'] instanceof String)) {
            throw new Error("Expected the field `updated_by` to be a primitive type in the JSON string but got " + data['updated_by']);
        }

        return true;
    }


}



/**
 * @member {String} completed_at
 */
DtoTaskResponse.prototype['completed_at'] = undefined;

/**
 * @member {String} created_at
 */
DtoTaskResponse.prototype['created_at'] = undefined;

/**
 * @member {String} created_by
 */
DtoTaskResponse.prototype['created_by'] = undefined;

/**
 * @member {module:model/TypesEntityType} entity_type
 */
DtoTaskResponse.prototype['entity_type'] = undefined;

/**
 * @member {String} error_summary
 */
DtoTaskResponse.prototype['error_summary'] = undefined;

/**
 * @member {String} failed_at
 */
DtoTaskResponse.prototype['failed_at'] = undefined;

/**
 * @member {Number} failed_records
 */
DtoTaskResponse.prototype['failed_records'] = undefined;

/**
 * @member {String} file_name
 */
DtoTaskResponse.prototype['file_name'] = undefined;

/**
 * @member {module:model/TypesFileType} file_type
 */
DtoTaskResponse.prototype['file_type'] = undefined;

/**
 * @member {String} file_url
 */
DtoTaskResponse.prototype['file_url'] = undefined;

/**
 * @member {String} id
 */
DtoTaskResponse.prototype['id'] = undefined;

/**
 * @member {Object.<String, Object>} metadata
 */
DtoTaskResponse.prototype['metadata'] = undefined;

/**
 * @member {Number} processed_records
 */
DtoTaskResponse.prototype['processed_records'] = undefined;

/**
 * @member {String} started_at
 */
DtoTaskResponse.prototype['started_at'] = undefined;

/**
 * @member {String} status
 */
DtoTaskResponse.prototype['status'] = undefined;

/**
 * @member {Number} successful_records
 */
DtoTaskResponse.prototype['successful_records'] = undefined;

/**
 * @member {module:model/TypesTaskStatus} task_status
 */
DtoTaskResponse.prototype['task_status'] = undefined;

/**
 * @member {module:model/TypesTaskType} task_type
 */
DtoTaskResponse.prototype['task_type'] = undefined;

/**
 * @member {String} tenant_id
 */
DtoTaskResponse.prototype['tenant_id'] = undefined;

/**
 * @member {Number} total_records
 */
DtoTaskResponse.prototype['total_records'] = undefined;

/**
 * @member {String} updated_at
 */
DtoTaskResponse.prototype['updated_at'] = undefined;

/**
 * @member {String} updated_by
 */
DtoTaskResponse.prototype['updated_by'] = undefined;






export default DtoTaskResponse;

