/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DtoUpdatePlanEntitlementRequest from './DtoUpdatePlanEntitlementRequest';
import DtoUpdatePlanPriceRequest from './DtoUpdatePlanPriceRequest';

/**
 * The DtoUpdatePlanRequest model module.
 * @module model/DtoUpdatePlanRequest
 * @version 1.0
 */
class DtoUpdatePlanRequest {
    /**
     * Constructs a new <code>DtoUpdatePlanRequest</code>.
     * @alias module:model/DtoUpdatePlanRequest
     */
    constructor() { 
        
        DtoUpdatePlanRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DtoUpdatePlanRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DtoUpdatePlanRequest} obj Optional instance to populate.
     * @return {module:model/DtoUpdatePlanRequest} The populated <code>DtoUpdatePlanRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DtoUpdatePlanRequest();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('entitlements')) {
                obj['entitlements'] = ApiClient.convertToType(data['entitlements'], [DtoUpdatePlanEntitlementRequest]);
            }
            if (data.hasOwnProperty('lookup_key')) {
                obj['lookup_key'] = ApiClient.convertToType(data['lookup_key'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('prices')) {
                obj['prices'] = ApiClient.convertToType(data['prices'], [DtoUpdatePlanPriceRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DtoUpdatePlanRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DtoUpdatePlanRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['entitlements']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['entitlements'])) {
                throw new Error("Expected the field `entitlements` to be an array in the JSON data but got " + data['entitlements']);
            }
            // validate the optional field `entitlements` (array)
            for (const item of data['entitlements']) {
                DtoUpdatePlanEntitlementRequest.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['lookup_key'] && !(typeof data['lookup_key'] === 'string' || data['lookup_key'] instanceof String)) {
            throw new Error("Expected the field `lookup_key` to be a primitive type in the JSON string but got " + data['lookup_key']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['prices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['prices'])) {
                throw new Error("Expected the field `prices` to be an array in the JSON data but got " + data['prices']);
            }
            // validate the optional field `prices` (array)
            for (const item of data['prices']) {
                DtoUpdatePlanPriceRequest.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} description
 */
DtoUpdatePlanRequest.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/DtoUpdatePlanEntitlementRequest>} entitlements
 */
DtoUpdatePlanRequest.prototype['entitlements'] = undefined;

/**
 * @member {String} lookup_key
 */
DtoUpdatePlanRequest.prototype['lookup_key'] = undefined;

/**
 * @member {String} name
 */
DtoUpdatePlanRequest.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/DtoUpdatePlanPriceRequest>} prices
 */
DtoUpdatePlanRequest.prototype['prices'] = undefined;






export default DtoUpdatePlanRequest;

