/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TypesBillingPeriod from './TypesBillingPeriod';
import TypesFeatureType from './TypesFeatureType';

/**
 * The DtoUpdatePlanEntitlementRequest model module.
 * @module model/DtoUpdatePlanEntitlementRequest
 * @version 1.0
 */
class DtoUpdatePlanEntitlementRequest {
    /**
     * Constructs a new <code>DtoUpdatePlanEntitlementRequest</code>.
     * @alias module:model/DtoUpdatePlanEntitlementRequest
     * @param featureId {String} 
     * @param featureType {module:model/TypesFeatureType} 
     */
    constructor(featureId, featureType) { 
        
        DtoUpdatePlanEntitlementRequest.initialize(this, featureId, featureType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, featureId, featureType) { 
        obj['feature_id'] = featureId;
        obj['feature_type'] = featureType;
    }

    /**
     * Constructs a <code>DtoUpdatePlanEntitlementRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DtoUpdatePlanEntitlementRequest} obj Optional instance to populate.
     * @return {module:model/DtoUpdatePlanEntitlementRequest} The populated <code>DtoUpdatePlanEntitlementRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DtoUpdatePlanEntitlementRequest();

            if (data.hasOwnProperty('feature_id')) {
                obj['feature_id'] = ApiClient.convertToType(data['feature_id'], 'String');
            }
            if (data.hasOwnProperty('feature_type')) {
                obj['feature_type'] = TypesFeatureType.constructFromObject(data['feature_type']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('is_soft_limit')) {
                obj['is_soft_limit'] = ApiClient.convertToType(data['is_soft_limit'], 'Boolean');
            }
            if (data.hasOwnProperty('plan_id')) {
                obj['plan_id'] = ApiClient.convertToType(data['plan_id'], 'String');
            }
            if (data.hasOwnProperty('static_value')) {
                obj['static_value'] = ApiClient.convertToType(data['static_value'], 'String');
            }
            if (data.hasOwnProperty('usage_limit')) {
                obj['usage_limit'] = ApiClient.convertToType(data['usage_limit'], 'Number');
            }
            if (data.hasOwnProperty('usage_reset_period')) {
                obj['usage_reset_period'] = TypesBillingPeriod.constructFromObject(data['usage_reset_period']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DtoUpdatePlanEntitlementRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DtoUpdatePlanEntitlementRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DtoUpdatePlanEntitlementRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['feature_id'] && !(typeof data['feature_id'] === 'string' || data['feature_id'] instanceof String)) {
            throw new Error("Expected the field `feature_id` to be a primitive type in the JSON string but got " + data['feature_id']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['plan_id'] && !(typeof data['plan_id'] === 'string' || data['plan_id'] instanceof String)) {
            throw new Error("Expected the field `plan_id` to be a primitive type in the JSON string but got " + data['plan_id']);
        }
        // ensure the json data is a string
        if (data['static_value'] && !(typeof data['static_value'] === 'string' || data['static_value'] instanceof String)) {
            throw new Error("Expected the field `static_value` to be a primitive type in the JSON string but got " + data['static_value']);
        }

        return true;
    }


}

DtoUpdatePlanEntitlementRequest.RequiredProperties = ["feature_id", "feature_type"];

/**
 * @member {String} feature_id
 */
DtoUpdatePlanEntitlementRequest.prototype['feature_id'] = undefined;

/**
 * @member {module:model/TypesFeatureType} feature_type
 */
DtoUpdatePlanEntitlementRequest.prototype['feature_type'] = undefined;

/**
 * The ID of the entitlement to update (present if the entitlement is being updated)
 * @member {String} id
 */
DtoUpdatePlanEntitlementRequest.prototype['id'] = undefined;

/**
 * @member {Boolean} is_enabled
 */
DtoUpdatePlanEntitlementRequest.prototype['is_enabled'] = undefined;

/**
 * @member {Boolean} is_soft_limit
 */
DtoUpdatePlanEntitlementRequest.prototype['is_soft_limit'] = undefined;

/**
 * @member {String} plan_id
 */
DtoUpdatePlanEntitlementRequest.prototype['plan_id'] = undefined;

/**
 * @member {String} static_value
 */
DtoUpdatePlanEntitlementRequest.prototype['static_value'] = undefined;

/**
 * @member {Number} usage_limit
 */
DtoUpdatePlanEntitlementRequest.prototype['usage_limit'] = undefined;

/**
 * @member {module:model/TypesBillingPeriod} usage_reset_period
 */
DtoUpdatePlanEntitlementRequest.prototype['usage_reset_period'] = undefined;






export default DtoUpdatePlanEntitlementRequest;

