/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TypesAutoTopupTrigger from './TypesAutoTopupTrigger';
import TypesStatus from './TypesStatus';
import TypesWalletConfig from './TypesWalletConfig';
import TypesWalletStatus from './TypesWalletStatus';
import TypesWalletType from './TypesWalletType';

/**
 * The DtoWalletBalanceResponse model module.
 * @module model/DtoWalletBalanceResponse
 * @version 1.0
 */
class DtoWalletBalanceResponse {
    /**
     * Constructs a new <code>DtoWalletBalanceResponse</code>.
     * @alias module:model/DtoWalletBalanceResponse
     */
    constructor() { 
        
        DtoWalletBalanceResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DtoWalletBalanceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DtoWalletBalanceResponse} obj Optional instance to populate.
     * @return {module:model/DtoWalletBalanceResponse} The populated <code>DtoWalletBalanceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DtoWalletBalanceResponse();

            if (data.hasOwnProperty('auto_topup_amount')) {
                obj['auto_topup_amount'] = ApiClient.convertToType(data['auto_topup_amount'], 'Number');
            }
            if (data.hasOwnProperty('auto_topup_min_balance')) {
                obj['auto_topup_min_balance'] = ApiClient.convertToType(data['auto_topup_min_balance'], 'Number');
            }
            if (data.hasOwnProperty('auto_topup_trigger')) {
                obj['auto_topup_trigger'] = TypesAutoTopupTrigger.constructFromObject(data['auto_topup_trigger']);
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
            if (data.hasOwnProperty('balance_updated_at')) {
                obj['balance_updated_at'] = ApiClient.convertToType(data['balance_updated_at'], 'String');
            }
            if (data.hasOwnProperty('config')) {
                obj['config'] = TypesWalletConfig.constructFromObject(data['config']);
            }
            if (data.hasOwnProperty('conversion_rate')) {
                obj['conversion_rate'] = ApiClient.convertToType(data['conversion_rate'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = ApiClient.convertToType(data['created_by'], 'String');
            }
            if (data.hasOwnProperty('credit_balance')) {
                obj['credit_balance'] = ApiClient.convertToType(data['credit_balance'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('current_period_usage')) {
                obj['current_period_usage'] = ApiClient.convertToType(data['current_period_usage'], 'Number');
            }
            if (data.hasOwnProperty('customer_id')) {
                obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('environment_id')) {
                obj['environment_id'] = ApiClient.convertToType(data['environment_id'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': 'String'});
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('real_time_balance')) {
                obj['real_time_balance'] = ApiClient.convertToType(data['real_time_balance'], 'Number');
            }
            if (data.hasOwnProperty('real_time_credit_balance')) {
                obj['real_time_credit_balance'] = ApiClient.convertToType(data['real_time_credit_balance'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = TypesStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
            if (data.hasOwnProperty('unpaid_invoice_amount')) {
                obj['unpaid_invoice_amount'] = ApiClient.convertToType(data['unpaid_invoice_amount'], 'Number');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('updated_by')) {
                obj['updated_by'] = ApiClient.convertToType(data['updated_by'], 'String');
            }
            if (data.hasOwnProperty('wallet_status')) {
                obj['wallet_status'] = TypesWalletStatus.constructFromObject(data['wallet_status']);
            }
            if (data.hasOwnProperty('wallet_type')) {
                obj['wallet_type'] = TypesWalletType.constructFromObject(data['wallet_type']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DtoWalletBalanceResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DtoWalletBalanceResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['balance_updated_at'] && !(typeof data['balance_updated_at'] === 'string' || data['balance_updated_at'] instanceof String)) {
            throw new Error("Expected the field `balance_updated_at` to be a primitive type in the JSON string but got " + data['balance_updated_at']);
        }
        // validate the optional field `config`
        if (data['config']) { // data not null
          TypesWalletConfig.validateJSON(data['config']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['created_by'] && !(typeof data['created_by'] === 'string' || data['created_by'] instanceof String)) {
            throw new Error("Expected the field `created_by` to be a primitive type in the JSON string but got " + data['created_by']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['customer_id'] && !(typeof data['customer_id'] === 'string' || data['customer_id'] instanceof String)) {
            throw new Error("Expected the field `customer_id` to be a primitive type in the JSON string but got " + data['customer_id']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['environment_id'] && !(typeof data['environment_id'] === 'string' || data['environment_id'] instanceof String)) {
            throw new Error("Expected the field `environment_id` to be a primitive type in the JSON string but got " + data['environment_id']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['tenant_id'] && !(typeof data['tenant_id'] === 'string' || data['tenant_id'] instanceof String)) {
            throw new Error("Expected the field `tenant_id` to be a primitive type in the JSON string but got " + data['tenant_id']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }
        // ensure the json data is a string
        if (data['updated_by'] && !(typeof data['updated_by'] === 'string' || data['updated_by'] instanceof String)) {
            throw new Error("Expected the field `updated_by` to be a primitive type in the JSON string but got " + data['updated_by']);
        }

        return true;
    }


}



/**
 * @member {Number} auto_topup_amount
 */
DtoWalletBalanceResponse.prototype['auto_topup_amount'] = undefined;

/**
 * @member {Number} auto_topup_min_balance
 */
DtoWalletBalanceResponse.prototype['auto_topup_min_balance'] = undefined;

/**
 * @member {module:model/TypesAutoTopupTrigger} auto_topup_trigger
 */
DtoWalletBalanceResponse.prototype['auto_topup_trigger'] = undefined;

/**
 * @member {Number} balance
 */
DtoWalletBalanceResponse.prototype['balance'] = undefined;

/**
 * @member {String} balance_updated_at
 */
DtoWalletBalanceResponse.prototype['balance_updated_at'] = undefined;

/**
 * @member {module:model/TypesWalletConfig} config
 */
DtoWalletBalanceResponse.prototype['config'] = undefined;

/**
 * @member {Number} conversion_rate
 */
DtoWalletBalanceResponse.prototype['conversion_rate'] = undefined;

/**
 * @member {String} created_at
 */
DtoWalletBalanceResponse.prototype['created_at'] = undefined;

/**
 * @member {String} created_by
 */
DtoWalletBalanceResponse.prototype['created_by'] = undefined;

/**
 * @member {Number} credit_balance
 */
DtoWalletBalanceResponse.prototype['credit_balance'] = undefined;

/**
 * @member {String} currency
 */
DtoWalletBalanceResponse.prototype['currency'] = undefined;

/**
 * @member {Number} current_period_usage
 */
DtoWalletBalanceResponse.prototype['current_period_usage'] = undefined;

/**
 * @member {String} customer_id
 */
DtoWalletBalanceResponse.prototype['customer_id'] = undefined;

/**
 * @member {String} description
 */
DtoWalletBalanceResponse.prototype['description'] = undefined;

/**
 * @member {String} environment_id
 */
DtoWalletBalanceResponse.prototype['environment_id'] = undefined;

/**
 * @member {String} id
 */
DtoWalletBalanceResponse.prototype['id'] = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
DtoWalletBalanceResponse.prototype['metadata'] = undefined;

/**
 * @member {String} name
 */
DtoWalletBalanceResponse.prototype['name'] = undefined;

/**
 * @member {Number} real_time_balance
 */
DtoWalletBalanceResponse.prototype['real_time_balance'] = undefined;

/**
 * @member {Number} real_time_credit_balance
 */
DtoWalletBalanceResponse.prototype['real_time_credit_balance'] = undefined;

/**
 * @member {module:model/TypesStatus} status
 */
DtoWalletBalanceResponse.prototype['status'] = undefined;

/**
 * @member {String} tenant_id
 */
DtoWalletBalanceResponse.prototype['tenant_id'] = undefined;

/**
 * @member {Number} unpaid_invoice_amount
 */
DtoWalletBalanceResponse.prototype['unpaid_invoice_amount'] = undefined;

/**
 * @member {String} updated_at
 */
DtoWalletBalanceResponse.prototype['updated_at'] = undefined;

/**
 * @member {String} updated_by
 */
DtoWalletBalanceResponse.prototype['updated_by'] = undefined;

/**
 * @member {module:model/TypesWalletStatus} wallet_status
 */
DtoWalletBalanceResponse.prototype['wallet_status'] = undefined;

/**
 * @member {module:model/TypesWalletType} wallet_type
 */
DtoWalletBalanceResponse.prototype['wallet_type'] = undefined;






export default DtoWalletBalanceResponse;

