/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GithubComFlexpriceFlexpriceInternalTypesValue model module.
 * @module model/GithubComFlexpriceFlexpriceInternalTypesValue
 * @version 1.0
 */
class GithubComFlexpriceFlexpriceInternalTypesValue {
    /**
     * Constructs a new <code>GithubComFlexpriceFlexpriceInternalTypesValue</code>.
     * @alias module:model/GithubComFlexpriceFlexpriceInternalTypesValue
     */
    constructor() { 
        
        GithubComFlexpriceFlexpriceInternalTypesValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GithubComFlexpriceFlexpriceInternalTypesValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GithubComFlexpriceFlexpriceInternalTypesValue} obj Optional instance to populate.
     * @return {module:model/GithubComFlexpriceFlexpriceInternalTypesValue} The populated <code>GithubComFlexpriceFlexpriceInternalTypesValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GithubComFlexpriceFlexpriceInternalTypesValue();

            if (data.hasOwnProperty('array')) {
                obj['array'] = ApiClient.convertToType(data['array'], ['String']);
            }
            if (data.hasOwnProperty('boolean')) {
                obj['boolean'] = ApiClient.convertToType(data['boolean'], 'Boolean');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('string')) {
                obj['string'] = ApiClient.convertToType(data['string'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GithubComFlexpriceFlexpriceInternalTypesValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GithubComFlexpriceFlexpriceInternalTypesValue</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['array'])) {
            throw new Error("Expected the field `array` to be an array in the JSON data but got " + data['array']);
        }
        // ensure the json data is a string
        if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
            throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
        }
        // ensure the json data is a string
        if (data['string'] && !(typeof data['string'] === 'string' || data['string'] instanceof String)) {
            throw new Error("Expected the field `string` to be a primitive type in the JSON string but got " + data['string']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} array
 */
GithubComFlexpriceFlexpriceInternalTypesValue.prototype['array'] = undefined;

/**
 * @member {Boolean} boolean
 */
GithubComFlexpriceFlexpriceInternalTypesValue.prototype['boolean'] = undefined;

/**
 * @member {String} date
 */
GithubComFlexpriceFlexpriceInternalTypesValue.prototype['date'] = undefined;

/**
 * @member {Number} number
 */
GithubComFlexpriceFlexpriceInternalTypesValue.prototype['number'] = undefined;

/**
 * @member {String} string
 */
GithubComFlexpriceFlexpriceInternalTypesValue.prototype['string'] = undefined;






export default GithubComFlexpriceFlexpriceInternalTypesValue;

