/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TypesPaymentDestinationType.
* @enum {}
* @readonly
*/
export default class TypesPaymentDestinationType {
    
        /**
         * value: "INVOICE"
         * @const
         */
        "PaymentDestinationTypeInvoice" = "INVOICE";

    

    /**
    * Returns a <code>TypesPaymentDestinationType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TypesPaymentDestinationType} The enum <code>TypesPaymentDestinationType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

