/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TypesEntityType.
* @enum {}
* @readonly
*/
export default class TypesEntityType {
    
        /**
         * value: "EVENTS"
         * @const
         */
        "EntityTypeEvents" = "EVENTS";

    
        /**
         * value: "PRICES"
         * @const
         */
        "EntityTypePrices" = "PRICES";

    
        /**
         * value: "CUSTOMERS"
         * @const
         */
        "EntityTypeCustomers" = "CUSTOMERS";

    

    /**
    * Returns a <code>TypesEntityType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TypesEntityType} The enum <code>TypesEntityType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

