/**
 * FlexPrice API
 * FlexPrice API Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TypesWalletStatus.
* @enum {}
* @readonly
*/
export default class TypesWalletStatus {
    
        /**
         * value: "active"
         * @const
         */
        "WalletStatusActive" = "active";

    
        /**
         * value: "frozen"
         * @const
         */
        "WalletStatusFrozen" = "frozen";

    
        /**
         * value: "closed"
         * @const
         */
        "WalletStatusClosed" = "closed";

    

    /**
    * Returns a <code>TypesWalletStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TypesWalletStatus} The enum <code>TypesWalletStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

