/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entityIntegrationMappingsCreateEntityIntegrationMapping } from "../funcs/entity-integration-mappings-create-entity-integration-mapping.js";
import { entityIntegrationMappingsDeleteEntityIntegrationMapping } from "../funcs/entity-integration-mappings-delete-entity-integration-mapping.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import * as models from "./models/index.js";

export class EntityIntegrationMappings extends ClientSDK {
  /**
   * Create entity integration mapping
   *
   * @remarks
   * Use when linking a FlexPrice entity to an external system (e.g. CRM or payment provider) so you can sync or reconcile by external ID.
   */
  async createEntityIntegrationMapping(
    request: models.DtoCreateEntityIntegrationMappingRequest,
    options?: RequestOptions,
  ): Promise<models.DtoEntityIntegrationMappingResponse> {
    return unwrapAsync(entityIntegrationMappingsCreateEntityIntegrationMapping(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete entity integration mapping
   *
   * @remarks
   * Use when unlinking a FlexPrice entity from an external system or cleaning up stale integration mappings.
   */
  async deleteEntityIntegrationMapping(
    id: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(entityIntegrationMappingsDeleteEntityIntegrationMapping(
      this,
      id,
      options,
    ));
  }
}
