/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsLinkIntegrationMapping } from "../funcs/integrations-link-integration-mapping.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import * as models from "./models/index.js";

export class Integrations extends ClientSDK {
  /**
   * Link integration mapping
   *
   * @remarks
   * Link a FlexPrice entity to provider entity with provider-specific side effects.
   */
  async linkIntegrationMapping(
    request: models.DtoLinkIntegrationMappingRequest,
    options?: RequestOptions,
  ): Promise<models.DtoLinkIntegrationMappingResponse> {
    return unwrapAsync(integrationsLinkIntegrationMapping(
      this,
      request,
      options,
    ));
  }
}
